// Central GI-typing augmentations.
//
// The `@girs` typings (generated by `ags types`) under-declare several GI
// members this codebase uses at runtime (gjs resolves them fine). These
// augmentations add the missing members so `tsc --noEmit` is clean WITHOUT
// changing any runtime call site. All are type-only — they cannot affect the
// running gjs/TINSHELL apps.
//
// The GI modules use `export namespace X` inside `declare module 'gi://...'`;
// we merge into that namespace (and, for class members, class+namespace merge
// for statics or interface merge for instance methods).

// ─── GObject: the signal-name fallback inherited `connect`/`emit` need ───
// `ags types` generates a per-type `X.SignalSignatures` holding that type's own
// signal names, but the `connect`/`emit` inherited from GObject.Object constrain
// their argument to the BASE block, which declares `notify` alone — so a
// connect("map") or connect("invalidate-contents") rejects a valid signal name,
// both in this tree and inside the ags/gnim shim sources under /usr/share/ags/js
// (the shims expose .ts, so skipLibCheck cannot exempt them). The generated
// top-level `SignalSignatures` already carries this fallback for dynamic signals.
declare module "gi://GObject?version=2.0" {
  export namespace GObject {
    export namespace Object {
      export interface SignalSignatures {
        [signal: string]: (...args: any[]) => any
      }
    }
  }
}
