/**
 * Emoji table — the SINGLE owner of emoji data in this home (Emoji 17.0,
 * CLDR short names). Generated from
 * https://unicode.org/Public/emoji/latest/emoji-test.txt
 * (fully-qualified single-codepoint + VS16 variants + flags; no ZWJ/skintone).
 * Sources: Smileys & Emotion, People & Body, Animals & Nature, Food & Drink,
 * Activities, Travel & Places, Flags. Extend by appending entries (or regenerate).
 * Keywords: name-derived + curated aliases for common searches.
 *
 * Consumers: the launcher's emoji mode (searchEntries in ./search.ts) — the
 * module is surface-agnostic (common/emoji/), so any surface ranks the same
 * table. Do NOT fork a copy — one table, one owner.
 */
export interface EmojiEntry {
  glyph: string
  name: string
  keywords: string[]
}

export const EMOJI: EmojiEntry[] = [
  { glyph: "😀", name: "grinning face", keywords: ["grinning", "face", "smile", "happy"] },
  {
    glyph: "😃",
    name: "grinning face with big eyes",
    keywords: ["grinning", "face", "big", "eyes"],
  },
  {
    glyph: "😄",
    name: "grinning face with smiling eyes",
    keywords: ["grinning", "face", "smiling", "eyes"],
  },
  {
    glyph: "😁",
    name: "beaming face with smiling eyes",
    keywords: ["beaming", "face", "smiling", "eyes", "smile", "happy"],
  },
  { glyph: "😆", name: "grinning squinting face", keywords: ["grinning", "squinting", "face"] },
  { glyph: "😅", name: "grinning face with sweat", keywords: ["grinning", "face", "sweat"] },
  {
    glyph: "🤣",
    name: "rolling on the floor laughing",
    keywords: ["rolling", "floor", "laughing", "laugh", "lol"],
  },
  {
    glyph: "😂",
    name: "face with tears of joy",
    keywords: ["face", "tears", "joy", "laugh", "lol"],
  },
  { glyph: "🙂", name: "slightly smiling face", keywords: ["slightly", "smiling", "face"] },
  { glyph: "🙃", name: "upside-down face", keywords: ["upsidedown", "face"] },
  { glyph: "🫠", name: "melting face", keywords: ["melting", "face"] },
  { glyph: "😉", name: "winking face", keywords: ["winking", "face", "wink"] },
  {
    glyph: "😊",
    name: "smiling face with smiling eyes",
    keywords: ["smiling", "face", "smiling", "eyes", "smile", "happy"],
  },
  {
    glyph: "😇",
    name: "smiling face with halo",
    keywords: ["smiling", "face", "halo", "angel", "innocent"],
  },
  {
    glyph: "🥰",
    name: "smiling face with hearts",
    keywords: ["smiling", "face", "hearts", "love"],
  },
  {
    glyph: "😍",
    name: "smiling face with heart-eyes",
    keywords: ["smiling", "face", "hearteyes", "love", "heart", "eyes"],
  },
  { glyph: "🤩", name: "star-struck", keywords: ["starstruck"] },
  { glyph: "😘", name: "face blowing a kiss", keywords: ["face", "blowing", "kiss", "love"] },
  { glyph: "😗", name: "kissing face", keywords: ["kissing", "face"] },
  { glyph: "☺️", name: "smiling face", keywords: ["smiling", "face"] },
  {
    glyph: "😚",
    name: "kissing face with closed eyes",
    keywords: ["kissing", "face", "closed", "eyes"],
  },
  {
    glyph: "😙",
    name: "kissing face with smiling eyes",
    keywords: ["kissing", "face", "smiling", "eyes"],
  },
  { glyph: "🥲", name: "smiling face with tear", keywords: ["smiling", "face", "tear"] },
  { glyph: "😋", name: "face savoring food", keywords: ["face", "savoring", "food"] },
  { glyph: "😛", name: "face with tongue", keywords: ["face", "tongue"] },
  {
    glyph: "😜",
    name: "winking face with tongue",
    keywords: ["winking", "face", "tongue", "crazy"],
  },
  { glyph: "🤪", name: "zany face", keywords: ["zany", "face", "crazy", "fun"] },
  { glyph: "😝", name: "squinting face with tongue", keywords: ["squinting", "face", "tongue"] },
  { glyph: "🤑", name: "money-mouth face", keywords: ["moneymouth", "face"] },
  {
    glyph: "🤗",
    name: "smiling face with open hands",
    keywords: ["smiling", "face", "open", "hands"],
  },
  { glyph: "🤭", name: "face with hand over mouth", keywords: ["face", "hand", "over", "mouth"] },
  {
    glyph: "🫢",
    name: "face with open eyes and hand over mouth",
    keywords: ["face", "open", "eyes", "hand", "over", "mouth"],
  },
  { glyph: "🫣", name: "face with peeking eye", keywords: ["face", "peeking", "eye"] },
  { glyph: "🤫", name: "shushing face", keywords: ["shushing", "face"] },
  { glyph: "🤔", name: "thinking face", keywords: ["thinking", "face", "think", "hmm"] },
  { glyph: "🫡", name: "saluting face", keywords: ["saluting", "face", "salute", "respect"] },
  { glyph: "🤐", name: "zipper-mouth face", keywords: ["zippermouth", "face"] },
  { glyph: "🤨", name: "face with raised eyebrow", keywords: ["face", "raised", "eyebrow"] },
  { glyph: "😐", name: "neutral face", keywords: ["neutral", "face"] },
  { glyph: "😑", name: "expressionless face", keywords: ["expressionless", "face"] },
  { glyph: "😶", name: "face without mouth", keywords: ["face", "without", "mouth"] },
  { glyph: "🫥", name: "dotted line face", keywords: ["dotted", "line", "face"] },
  { glyph: "😏", name: "smirking face", keywords: ["smirking", "face"] },
  { glyph: "😒", name: "unamused face", keywords: ["unamused", "face"] },
  { glyph: "🙄", name: "face with rolling eyes", keywords: ["face", "rolling", "eyes"] },
  { glyph: "😬", name: "grimacing face", keywords: ["grimacing", "face", "awkward", "cringe"] },
  { glyph: "🤥", name: "lying face", keywords: ["lying", "face"] },
  { glyph: "🫨", name: "shaking face", keywords: ["shaking", "face"] },
  { glyph: "😌", name: "relieved face", keywords: ["relieved", "face"] },
  { glyph: "😔", name: "pensive face", keywords: ["pensive", "face"] },
  { glyph: "😪", name: "sleepy face", keywords: ["sleepy", "face"] },
  { glyph: "🤤", name: "drooling face", keywords: ["drooling", "face", "drool", "yummy"] },
  { glyph: "😴", name: "sleeping face", keywords: ["sleeping", "face", "sleep", "tired"] },
  { glyph: "🫩", name: "face with bags under eyes", keywords: ["face", "bags", "under", "eyes"] },
  { glyph: "😷", name: "face with medical mask", keywords: ["face", "medical", "mask"] },
  {
    glyph: "🤒",
    name: "face with thermometer",
    keywords: ["face", "thermometer", "sick", "fever"],
  },
  {
    glyph: "🤕",
    name: "face with head-bandage",
    keywords: ["face", "headbandage", "hurt", "injury"],
  },
  { glyph: "🤢", name: "nauseated face", keywords: ["nauseated", "face", "sick", "vomit"] },
  { glyph: "🤮", name: "face vomiting", keywords: ["face", "vomiting"] },
  { glyph: "🤧", name: "sneezing face", keywords: ["sneezing", "face", "sick", "sneeze"] },
  { glyph: "🥵", name: "hot face", keywords: ["hot", "face"] },
  { glyph: "🥶", name: "cold face", keywords: ["cold", "face"] },
  { glyph: "🥴", name: "woozy face", keywords: ["woozy", "face"] },
  { glyph: "😵", name: "face with crossed-out eyes", keywords: ["face", "crossedout", "eyes"] },
  {
    glyph: "🤯",
    name: "exploding head",
    keywords: ["exploding", "head", "mind", "blown", "shock"],
  },
  { glyph: "🤠", name: "cowboy hat face", keywords: ["cowboy", "hat", "face"] },
  { glyph: "🥳", name: "partying face", keywords: ["partying", "face", "party", "celebrate"] },
  { glyph: "🥸", name: "disguised face", keywords: ["disguised", "face"] },
  {
    glyph: "😎",
    name: "smiling face with sunglasses",
    keywords: ["smiling", "face", "sunglasses", "cool"],
  },
  { glyph: "🤓", name: "nerd face", keywords: ["nerd", "face", "geek"] },
  { glyph: "🧐", name: "face with monocle", keywords: ["face", "monocle"] },
  { glyph: "😕", name: "confused face", keywords: ["confused", "face"] },
  { glyph: "🫤", name: "face with diagonal mouth", keywords: ["face", "diagonal", "mouth"] },
  { glyph: "😟", name: "worried face", keywords: ["worried", "face"] },
  { glyph: "🙁", name: "slightly frowning face", keywords: ["slightly", "frowning", "face"] },
  { glyph: "☹️", name: "frowning face", keywords: ["frowning", "face"] },
  { glyph: "😮", name: "face with open mouth", keywords: ["face", "open", "mouth"] },
  { glyph: "😯", name: "hushed face", keywords: ["hushed", "face"] },
  { glyph: "😲", name: "astonished face", keywords: ["astonished", "face"] },
  { glyph: "😳", name: "flushed face", keywords: ["flushed", "face"] },
  { glyph: "🫪", name: "distorted face", keywords: ["distorted", "face"] },
  { glyph: "🥺", name: "pleading face", keywords: ["pleading", "face", "please", "beg"] },
  { glyph: "🥹", name: "face holding back tears", keywords: ["face", "holding", "back", "tears"] },
  {
    glyph: "😦",
    name: "frowning face with open mouth",
    keywords: ["frowning", "face", "open", "mouth"],
  },
  { glyph: "😧", name: "anguished face", keywords: ["anguished", "face"] },
  { glyph: "😨", name: "fearful face", keywords: ["fearful", "face"] },
  { glyph: "😰", name: "anxious face with sweat", keywords: ["anxious", "face", "sweat"] },
  { glyph: "😥", name: "sad but relieved face", keywords: ["sad", "but", "relieved", "face"] },
  { glyph: "😢", name: "crying face", keywords: ["crying", "face", "sad", "cry", "tear"] },
  {
    glyph: "😭",
    name: "loudly crying face",
    keywords: ["loudly", "crying", "face", "cry", "sad", "tear"],
  },
  {
    glyph: "😱",
    name: "face screaming in fear",
    keywords: ["face", "screaming", "fear", "scared", "shock", "scream"],
  },
  { glyph: "😖", name: "confounded face", keywords: ["confounded", "face"] },
  { glyph: "😣", name: "persevering face", keywords: ["persevering", "face"] },
  { glyph: "😞", name: "disappointed face", keywords: ["disappointed", "face"] },
  { glyph: "😓", name: "downcast face with sweat", keywords: ["downcast", "face", "sweat"] },
  { glyph: "😩", name: "weary face", keywords: ["weary", "face"] },
  { glyph: "😫", name: "tired face", keywords: ["tired", "face"] },
  { glyph: "🥱", name: "yawning face", keywords: ["yawning", "face"] },
  { glyph: "😤", name: "face with steam from nose", keywords: ["face", "steam", "from", "nose"] },
  { glyph: "😡", name: "enraged face", keywords: ["enraged", "face", "angry", "mad"] },
  { glyph: "😠", name: "angry face", keywords: ["angry", "face", "mad"] },
  { glyph: "🤬", name: "face with symbols on mouth", keywords: ["face", "symbols", "mouth"] },
  { glyph: "😈", name: "smiling face with horns", keywords: ["smiling", "face", "horns"] },
  { glyph: "👿", name: "angry face with horns", keywords: ["angry", "face", "horns"] },
  { glyph: "💀", name: "skull", keywords: ["skull"] },
  { glyph: "☠️", name: "skull and crossbones", keywords: ["skull", "crossbones"] },
  { glyph: "💩", name: "pile of poo", keywords: ["pile", "poo"] },
  { glyph: "🤡", name: "clown face", keywords: ["clown", "face"] },
  { glyph: "👹", name: "ogre", keywords: ["ogre"] },
  { glyph: "👺", name: "goblin", keywords: ["goblin"] },
  { glyph: "👻", name: "ghost", keywords: ["ghost"] },
  { glyph: "👽", name: "alien", keywords: ["alien"] },
  { glyph: "👾", name: "alien monster", keywords: ["alien", "monster"] },
  { glyph: "🤖", name: "robot", keywords: ["robot"] },
  { glyph: "😺", name: "grinning cat", keywords: ["grinning", "cat"] },
  {
    glyph: "😸",
    name: "grinning cat with smiling eyes",
    keywords: ["grinning", "cat", "smiling", "eyes"],
  },
  { glyph: "😹", name: "cat with tears of joy", keywords: ["cat", "tears", "joy"] },
  { glyph: "😻", name: "smiling cat with heart-eyes", keywords: ["smiling", "cat", "hearteyes"] },
  { glyph: "😼", name: "cat with wry smile", keywords: ["cat", "wry", "smile"] },
  { glyph: "😽", name: "kissing cat", keywords: ["kissing", "cat"] },
  { glyph: "🙀", name: "weary cat", keywords: ["weary", "cat"] },
  { glyph: "😿", name: "crying cat", keywords: ["crying", "cat"] },
  { glyph: "😾", name: "pouting cat", keywords: ["pouting", "cat"] },
  { glyph: "🙈", name: "see-no-evil monkey", keywords: ["seenoevil", "monkey", "hide", "see"] },
  { glyph: "🙉", name: "hear-no-evil monkey", keywords: ["hearnoevil", "monkey", "hear"] },
  {
    glyph: "🙊",
    name: "speak-no-evil monkey",
    keywords: ["speaknoevil", "monkey", "speak", "quiet"],
  },
  { glyph: "💌", name: "love letter", keywords: ["love", "letter"] },
  { glyph: "💘", name: "heart with arrow", keywords: ["heart", "arrow"] },
  { glyph: "💝", name: "heart with ribbon", keywords: ["heart", "ribbon"] },
  { glyph: "💖", name: "sparkling heart", keywords: ["sparkling", "heart"] },
  { glyph: "💗", name: "growing heart", keywords: ["growing", "heart"] },
  { glyph: "💓", name: "beating heart", keywords: ["beating", "heart"] },
  { glyph: "💞", name: "revolving hearts", keywords: ["revolving", "hearts"] },
  { glyph: "💕", name: "two hearts", keywords: ["two", "hearts"] },
  { glyph: "💟", name: "heart decoration", keywords: ["heart", "decoration"] },
  { glyph: "❣️", name: "heart exclamation", keywords: ["heart", "exclamation"] },
  { glyph: "💔", name: "broken heart", keywords: ["broken", "heart", "sad"] },
  { glyph: "❤️", name: "red heart", keywords: ["red", "heart", "love"] },
  { glyph: "🩷", name: "pink heart", keywords: ["pink", "heart"] },
  { glyph: "🧡", name: "orange heart", keywords: ["orange", "heart", "love"] },
  { glyph: "💛", name: "yellow heart", keywords: ["yellow", "heart", "love"] },
  { glyph: "💚", name: "green heart", keywords: ["green", "heart", "love"] },
  { glyph: "💙", name: "blue heart", keywords: ["blue", "heart", "love"] },
  { glyph: "🩵", name: "light blue heart", keywords: ["light", "blue", "heart"] },
  { glyph: "💜", name: "purple heart", keywords: ["purple", "heart", "love"] },
  { glyph: "🤎", name: "brown heart", keywords: ["brown", "heart"] },
  { glyph: "🖤", name: "black heart", keywords: ["black", "heart", "love"] },
  { glyph: "🩶", name: "grey heart", keywords: ["grey", "heart"] },
  { glyph: "🤍", name: "white heart", keywords: ["white", "heart"] },
  { glyph: "💋", name: "kiss mark", keywords: ["kiss", "mark"] },
  { glyph: "💯", name: "hundred points", keywords: ["hundred", "points", "perfect", "awesome"] },
  { glyph: "💢", name: "anger symbol", keywords: ["anger", "symbol"] },
  { glyph: "🫯", name: "fight cloud", keywords: ["fight", "cloud"] },
  { glyph: "💥", name: "collision", keywords: ["collision", "boom", "explosion", "impact"] },
  { glyph: "💫", name: "dizzy", keywords: ["dizzy"] },
  { glyph: "💦", name: "sweat droplets", keywords: ["sweat", "droplets", "water", "splash"] },
  { glyph: "💨", name: "dashing away", keywords: ["dashing", "away"] },
  { glyph: "🕳️", name: "hole", keywords: ["hole"] },
  { glyph: "💬", name: "speech balloon", keywords: ["speech", "balloon"] },
  { glyph: "🗨️", name: "left speech bubble", keywords: ["left", "speech", "bubble"] },
  { glyph: "🗯️", name: "right anger bubble", keywords: ["right", "anger", "bubble"] },
  { glyph: "💭", name: "thought balloon", keywords: ["thought", "balloon"] },
  { glyph: "💤", name: "ZZZ", keywords: ["zzz"] },
  { glyph: "👋", name: "waving hand", keywords: ["waving", "hand", "wave", "hello", "bye", "hi"] },
  { glyph: "🤚", name: "raised back of hand", keywords: ["raised", "back", "hand"] },
  {
    glyph: "🖐️",
    name: "hand with fingers splayed",
    keywords: ["hand", "fingers", "splayed", "five"],
  },
  { glyph: "✋", name: "raised hand", keywords: ["raised", "hand", "stop"] },
  { glyph: "🖖", name: "vulcan salute", keywords: ["vulcan", "salute"] },
  { glyph: "🫱", name: "rightwards hand", keywords: ["rightwards", "hand"] },
  { glyph: "🫲", name: "leftwards hand", keywords: ["leftwards", "hand"] },
  { glyph: "🫳", name: "palm down hand", keywords: ["palm", "hand"] },
  { glyph: "🫴", name: "palm up hand", keywords: ["palm", "hand"] },
  { glyph: "🫷", name: "leftwards pushing hand", keywords: ["leftwards", "pushing", "hand"] },
  { glyph: "🫸", name: "rightwards pushing hand", keywords: ["rightwards", "pushing", "hand"] },
  { glyph: "👌", name: "OK hand", keywords: ["hand", "ok", "perfect", "fine"] },
  { glyph: "🤌", name: "pinched fingers", keywords: ["pinched", "fingers"] },
  { glyph: "🤏", name: "pinching hand", keywords: ["pinching", "hand"] },
  { glyph: "✌️", name: "victory hand", keywords: ["victory", "hand", "peace", "v"] },
  { glyph: "🤞", name: "crossed fingers", keywords: ["crossed", "fingers", "luck"] },
  {
    glyph: "🫰",
    name: "hand with index finger and thumb crossed",
    keywords: ["hand", "index", "finger", "thumb", "crossed"],
  },
  { glyph: "🤟", name: "love-you gesture", keywords: ["loveyou", "gesture"] },
  { glyph: "🤘", name: "sign of the horns", keywords: ["sign", "horns"] },
  { glyph: "🤙", name: "call me hand", keywords: ["call", "hand"] },
  {
    glyph: "👈",
    name: "backhand index pointing left",
    keywords: ["backhand", "index", "pointing", "left"],
  },
  {
    glyph: "👉",
    name: "backhand index pointing right",
    keywords: ["backhand", "index", "pointing", "right"],
  },
  { glyph: "👆", name: "backhand index pointing up", keywords: ["backhand", "index", "pointing"] },
  { glyph: "🖕", name: "middle finger", keywords: ["middle", "finger"] },
  {
    glyph: "👇",
    name: "backhand index pointing down",
    keywords: ["backhand", "index", "pointing"],
  },
  { glyph: "☝️", name: "index pointing up", keywords: ["index", "pointing"] },
  { glyph: "🫵", name: "index pointing at the viewer", keywords: ["index", "pointing", "viewer"] },
  { glyph: "👍", name: "thumbs up", keywords: ["thumbs", "yes", "good", "ok", "approve", "thumb"] },
  { glyph: "👎", name: "thumbs down", keywords: ["thumbs", "no", "bad", "thumb", "dislike"] },
  { glyph: "✊", name: "raised fist", keywords: ["raised", "fist"] },
  { glyph: "👊", name: "oncoming fist", keywords: ["oncoming", "fist"] },
  { glyph: "🤛", name: "left-facing fist", keywords: ["leftfacing", "fist"] },
  { glyph: "🤜", name: "right-facing fist", keywords: ["rightfacing", "fist"] },
  { glyph: "👏", name: "clapping hands", keywords: ["clapping", "hands", "clap", "applause"] },
  { glyph: "🙌", name: "raising hands", keywords: ["raising", "hands"] },
  { glyph: "🫶", name: "heart hands", keywords: ["heart", "hands", "love"] },
  { glyph: "👐", name: "open hands", keywords: ["open", "hands"] },
  { glyph: "🤲", name: "palms up together", keywords: ["palms", "together"] },
  { glyph: "🤝", name: "handshake", keywords: ["handshake", "deal", "agree", "hi"] },
  {
    glyph: "🙏",
    name: "folded hands",
    keywords: ["folded", "hands", "please", "thank", "thanks", "pray", "sorry"],
  },
  { glyph: "✍️", name: "writing hand", keywords: ["writing", "hand", "write", "sign"] },
  { glyph: "💅", name: "nail polish", keywords: ["nail", "polish", "nails", "manicure", "done"] },
  { glyph: "🤳", name: "selfie", keywords: ["selfie"] },
  {
    glyph: "💪",
    name: "flexed biceps",
    keywords: ["flexed", "biceps", "muscle", "strong", "arm", "gym"],
  },
  { glyph: "🦾", name: "mechanical arm", keywords: ["mechanical", "arm"] },
  { glyph: "🦿", name: "mechanical leg", keywords: ["mechanical", "leg"] },
  { glyph: "🦵", name: "leg", keywords: ["leg"] },
  { glyph: "🦶", name: "foot", keywords: ["foot"] },
  { glyph: "👂", name: "ear", keywords: ["ear", "listen", "hear"] },
  { glyph: "🦻", name: "ear with hearing aid", keywords: ["ear", "hearing", "aid"] },
  { glyph: "👃", name: "nose", keywords: ["nose"] },
  { glyph: "🧠", name: "brain", keywords: ["brain", "mind", "think"] },
  { glyph: "🫀", name: "anatomical heart", keywords: ["anatomical", "heart"] },
  { glyph: "🫁", name: "lungs", keywords: ["lungs"] },
  { glyph: "🦷", name: "tooth", keywords: ["tooth", "teeth", "dentist"] },
  { glyph: "🦴", name: "bone", keywords: ["bone"] },
  { glyph: "👀", name: "eyes", keywords: ["eyes", "look", "see"] },
  { glyph: "👁️", name: "eye", keywords: ["eye"] },
  { glyph: "👅", name: "tongue", keywords: ["tongue", "lick"] },
  { glyph: "👄", name: "mouth", keywords: ["mouth", "lips", "kiss"] },
  { glyph: "🫦", name: "biting lip", keywords: ["biting", "lip"] },
  { glyph: "👶", name: "baby", keywords: ["baby"] },
  { glyph: "🧒", name: "child", keywords: ["child"] },
  { glyph: "👦", name: "boy", keywords: ["boy"] },
  { glyph: "👧", name: "girl", keywords: ["girl"] },
  { glyph: "🧑", name: "person", keywords: ["person"] },
  { glyph: "👱", name: "person: blond hair", keywords: ["person", "blond", "hair"] },
  { glyph: "👨", name: "man", keywords: ["man"] },
  { glyph: "🧔", name: "person: beard", keywords: ["person", "beard"] },
  { glyph: "👩", name: "woman", keywords: ["woman"] },
  { glyph: "🧓", name: "older person", keywords: ["older", "person"] },
  { glyph: "👴", name: "old man", keywords: ["old", "man"] },
  { glyph: "👵", name: "old woman", keywords: ["old", "woman"] },
  { glyph: "🙍", name: "person frowning", keywords: ["person", "frowning"] },
  { glyph: "🙎", name: "person pouting", keywords: ["person", "pouting"] },
  { glyph: "🙅", name: "person gesturing NO", keywords: ["person", "gesturing"] },
  { glyph: "🙆", name: "person gesturing OK", keywords: ["person", "gesturing"] },
  { glyph: "💁", name: "person tipping hand", keywords: ["person", "tipping", "hand"] },
  { glyph: "🙋", name: "person raising hand", keywords: ["person", "raising", "hand"] },
  { glyph: "🧏", name: "deaf person", keywords: ["deaf", "person", "hearing"] },
  { glyph: "🙇", name: "person bowing", keywords: ["person", "bowing"] },
  { glyph: "🤦", name: "person facepalming", keywords: ["person", "facepalming"] },
  { glyph: "🤷", name: "person shrugging", keywords: ["person", "shrugging"] },
  { glyph: "👮", name: "police officer", keywords: ["police", "officer"] },
  { glyph: "🕵️", name: "detective", keywords: ["detective"] },
  { glyph: "💂", name: "guard", keywords: ["guard"] },
  { glyph: "🥷", name: "ninja", keywords: ["ninja"] },
  { glyph: "👷", name: "construction worker", keywords: ["construction", "worker"] },
  { glyph: "🫅", name: "person with crown", keywords: ["person", "crown"] },
  { glyph: "🤴", name: "prince", keywords: ["prince"] },
  { glyph: "👸", name: "princess", keywords: ["princess"] },
  { glyph: "👳", name: "person wearing turban", keywords: ["person", "wearing", "turban"] },
  { glyph: "👲", name: "person with skullcap", keywords: ["person", "skullcap"] },
  { glyph: "🧕", name: "woman with headscarf", keywords: ["woman", "headscarf"] },
  { glyph: "🤵", name: "person in tuxedo", keywords: ["person", "tuxedo"] },
  { glyph: "👰", name: "person with veil", keywords: ["person", "veil"] },
  { glyph: "🤰", name: "pregnant woman", keywords: ["pregnant", "woman"] },
  { glyph: "🫃", name: "pregnant man", keywords: ["pregnant", "man"] },
  { glyph: "🫄", name: "pregnant person", keywords: ["pregnant", "person"] },
  { glyph: "🤱", name: "breast-feeding", keywords: ["breastfeeding"] },
  { glyph: "👼", name: "baby angel", keywords: ["baby", "angel"] },
  { glyph: "🎅", name: "Santa Claus", keywords: ["santa", "claus"] },
  { glyph: "🤶", name: "Mrs. Claus", keywords: ["mrs", "claus"] },
  { glyph: "🦸", name: "superhero", keywords: ["superhero"] },
  { glyph: "🦹", name: "supervillain", keywords: ["supervillain"] },
  { glyph: "🧙", name: "mage", keywords: ["mage"] },
  { glyph: "🧚", name: "fairy", keywords: ["fairy"] },
  { glyph: "🧛", name: "vampire", keywords: ["vampire"] },
  { glyph: "🧜", name: "merperson", keywords: ["merperson"] },
  { glyph: "🧝", name: "elf", keywords: ["elf"] },
  { glyph: "🧞", name: "genie", keywords: ["genie"] },
  { glyph: "🧟", name: "zombie", keywords: ["zombie"] },
  { glyph: "🧌", name: "troll", keywords: ["troll"] },
  { glyph: "🫈", name: "hairy creature", keywords: ["hairy", "creature"] },
  { glyph: "💆", name: "person getting massage", keywords: ["person", "getting", "massage"] },
  { glyph: "💇", name: "person getting haircut", keywords: ["person", "getting", "haircut"] },
  { glyph: "🚶", name: "person walking", keywords: ["person", "walking", "walk"] },
  { glyph: "🧍", name: "person standing", keywords: ["person", "standing"] },
  { glyph: "🧎", name: "person kneeling", keywords: ["person", "kneeling"] },
  { glyph: "🏃", name: "person running", keywords: ["person", "running", "run", "sprint"] },
  { glyph: "💃", name: "woman dancing", keywords: ["woman", "dancing"] },
  { glyph: "🕺", name: "man dancing", keywords: ["man", "dancing"] },
  { glyph: "🕴️", name: "person in suit levitating", keywords: ["person", "suit", "levitating"] },
  { glyph: "👯", name: "people with bunny ears", keywords: ["people", "bunny", "ears"] },
  { glyph: "🧖", name: "person in steamy room", keywords: ["person", "steamy", "room"] },
  { glyph: "🧗", name: "person climbing", keywords: ["person", "climbing"] },
  { glyph: "🤺", name: "person fencing", keywords: ["person", "fencing"] },
  { glyph: "🏇", name: "horse racing", keywords: ["horse", "racing"] },
  { glyph: "⛷️", name: "skier", keywords: ["skier"] },
  { glyph: "🏂", name: "snowboarder", keywords: ["snowboarder", "snowboard", "snow"] },
  { glyph: "🏌️", name: "person golfing", keywords: ["person", "golfing", "golf", "golfer"] },
  { glyph: "🏄", name: "person surfing", keywords: ["person", "surfing", "surf"] },
  { glyph: "🚣", name: "person rowing boat", keywords: ["person", "rowing", "boat", "row"] },
  { glyph: "🏊", name: "person swimming", keywords: ["person", "swimming", "swim"] },
  {
    glyph: "⛹️",
    name: "person bouncing ball",
    keywords: ["person", "bouncing", "ball", "basketball"],
  },
  {
    glyph: "🏋️",
    name: "person lifting weights",
    keywords: ["person", "lifting", "weights", "gym", "weight", "lift", "workout"],
  },
  {
    glyph: "🚴",
    name: "person biking",
    keywords: ["person", "biking", "bike", "cycling", "cyclist"],
  },
  {
    glyph: "🚵",
    name: "person mountain biking",
    keywords: ["person", "mountain", "biking", "bike", "cycling"],
  },
  {
    glyph: "🤸",
    name: "person cartwheeling",
    keywords: ["person", "cartwheeling", "cartwheel", "gymnastics"],
  },
  { glyph: "🤼", name: "people wrestling", keywords: ["people", "wrestling"] },
  {
    glyph: "🤽",
    name: "person playing water polo",
    keywords: ["person", "playing", "water", "polo"],
  },
  { glyph: "🤾", name: "person playing handball", keywords: ["person", "playing", "handball"] },
  { glyph: "🤹", name: "person juggling", keywords: ["person", "juggling"] },
  {
    glyph: "🧘",
    name: "person in lotus position",
    keywords: ["person", "lotus", "position", "yoga", "meditation"],
  },
  { glyph: "🛀", name: "person taking bath", keywords: ["person", "taking", "bath"] },
  { glyph: "🛌", name: "person in bed", keywords: ["person", "bed"] },
  { glyph: "👭", name: "women holding hands", keywords: ["women", "holding", "hands"] },
  {
    glyph: "👫",
    name: "woman and man holding hands",
    keywords: ["woman", "man", "holding", "hands"],
  },
  { glyph: "👬", name: "men holding hands", keywords: ["men", "holding", "hands"] },
  { glyph: "💏", name: "kiss", keywords: ["kiss"] },
  { glyph: "💑", name: "couple with heart", keywords: ["couple", "heart"] },
  { glyph: "🗣️", name: "speaking head", keywords: ["speaking", "head"] },
  { glyph: "👤", name: "bust in silhouette", keywords: ["bust", "silhouette"] },
  { glyph: "👥", name: "busts in silhouette", keywords: ["busts", "silhouette"] },
  { glyph: "🫂", name: "people hugging", keywords: ["people", "hugging"] },
  { glyph: "👪", name: "family", keywords: ["family"] },
  { glyph: "👣", name: "footprints", keywords: ["footprints"] },
  { glyph: "🫆", name: "fingerprint", keywords: ["fingerprint"] },
  { glyph: "🐵", name: "monkey face", keywords: ["monkey", "face"] },
  { glyph: "🐒", name: "monkey", keywords: ["monkey"] },
  { glyph: "🦍", name: "gorilla", keywords: ["gorilla"] },
  { glyph: "🦧", name: "orangutan", keywords: ["orangutan"] },
  { glyph: "🐶", name: "dog face", keywords: ["dog", "face", "puppy"] },
  { glyph: "🐕", name: "dog", keywords: ["dog"] },
  { glyph: "🦮", name: "guide dog", keywords: ["guide", "dog"] },
  { glyph: "🐩", name: "poodle", keywords: ["poodle"] },
  { glyph: "🐺", name: "wolf", keywords: ["wolf"] },
  { glyph: "🦊", name: "fox", keywords: ["fox"] },
  { glyph: "🦝", name: "raccoon", keywords: ["raccoon"] },
  { glyph: "🐱", name: "cat face", keywords: ["cat", "face", "kitty", "kitten"] },
  { glyph: "🐈", name: "cat", keywords: ["cat"] },
  { glyph: "🦁", name: "lion", keywords: ["lion"] },
  { glyph: "🐯", name: "tiger face", keywords: ["tiger", "face"] },
  { glyph: "🐅", name: "tiger", keywords: ["tiger"] },
  { glyph: "🐆", name: "leopard", keywords: ["leopard", "cheetah"] },
  { glyph: "🐴", name: "horse face", keywords: ["horse", "face"] },
  { glyph: "🫎", name: "moose", keywords: ["moose"] },
  { glyph: "🫏", name: "donkey", keywords: ["donkey"] },
  { glyph: "🐎", name: "horse", keywords: ["horse"] },
  { glyph: "🦄", name: "unicorn", keywords: ["unicorn"] },
  { glyph: "🦓", name: "zebra", keywords: ["zebra"] },
  { glyph: "🦌", name: "deer", keywords: ["deer"] },
  { glyph: "🦬", name: "bison", keywords: ["bison"] },
  { glyph: "🐮", name: "cow face", keywords: ["cow", "face"] },
  { glyph: "🐃", name: "water buffalo", keywords: ["water", "buffalo"] },
  { glyph: "🐄", name: "cow", keywords: ["cow"] },
  { glyph: "🐷", name: "pig face", keywords: ["pig", "face"] },
  { glyph: "🐖", name: "pig", keywords: ["pig"] },
  { glyph: "🐗", name: "boar", keywords: ["boar", "pig"] },
  { glyph: "🐽", name: "pig nose", keywords: ["pig", "nose"] },
  { glyph: "🐏", name: "ram", keywords: ["ram"] },
  { glyph: "🐑", name: "ewe", keywords: ["ewe"] },
  { glyph: "🐐", name: "goat", keywords: ["goat"] },
  { glyph: "🐪", name: "camel", keywords: ["camel"] },
  { glyph: "🐫", name: "two-hump camel", keywords: ["twohump", "camel", "two"] },
  { glyph: "🦙", name: "llama", keywords: ["llama"] },
  { glyph: "🦒", name: "giraffe", keywords: ["giraffe"] },
  { glyph: "🐘", name: "elephant", keywords: ["elephant"] },
  { glyph: "🦣", name: "mammoth", keywords: ["mammoth"] },
  { glyph: "🦏", name: "rhinoceros", keywords: ["rhinoceros", "rhino"] },
  { glyph: "🦛", name: "hippopotamus", keywords: ["hippopotamus", "hippo"] },
  { glyph: "🐭", name: "mouse face", keywords: ["mouse", "face", "rat"] },
  { glyph: "🐁", name: "mouse", keywords: ["mouse"] },
  { glyph: "🐀", name: "rat", keywords: ["rat"] },
  { glyph: "🐹", name: "hamster", keywords: ["hamster"] },
  { glyph: "🐰", name: "rabbit face", keywords: ["rabbit", "face", "bunny"] },
  { glyph: "🐇", name: "rabbit", keywords: ["rabbit", "bunny"] },
  { glyph: "🐿️", name: "chipmunk", keywords: ["chipmunk", "squirrel"] },
  { glyph: "🦫", name: "beaver", keywords: ["beaver"] },
  { glyph: "🦔", name: "hedgehog", keywords: ["hedgehog"] },
  { glyph: "🦇", name: "bat", keywords: ["bat"] },
  { glyph: "🐻", name: "bear", keywords: ["bear"] },
  { glyph: "🐨", name: "koala", keywords: ["koala"] },
  { glyph: "🐼", name: "panda", keywords: ["panda"] },
  { glyph: "🦥", name: "sloth", keywords: ["sloth"] },
  { glyph: "🦦", name: "otter", keywords: ["otter"] },
  { glyph: "🦨", name: "skunk", keywords: ["skunk"] },
  { glyph: "🦘", name: "kangaroo", keywords: ["kangaroo"] },
  { glyph: "🦡", name: "badger", keywords: ["badger"] },
  { glyph: "🐾", name: "paw prints", keywords: ["paw", "prints", "paws", "footprints"] },
  { glyph: "🦃", name: "turkey", keywords: ["turkey"] },
  { glyph: "🐔", name: "chicken", keywords: ["chicken", "hen"] },
  { glyph: "🐓", name: "rooster", keywords: ["rooster", "chicken"] },
  { glyph: "🐣", name: "hatching chick", keywords: ["hatching", "chick", "hatch", "egg"] },
  { glyph: "🐤", name: "baby chick", keywords: ["baby", "chick", "bird"] },
  {
    glyph: "🐥",
    name: "front-facing baby chick",
    keywords: ["frontfacing", "baby", "chick", "bird"],
  },
  { glyph: "🐦", name: "bird", keywords: ["bird"] },
  { glyph: "🐧", name: "penguin", keywords: ["penguin"] },
  { glyph: "🕊️", name: "dove", keywords: ["dove"] },
  { glyph: "🦅", name: "eagle", keywords: ["eagle"] },
  { glyph: "🦆", name: "duck", keywords: ["duck"] },
  { glyph: "🦢", name: "swan", keywords: ["swan"] },
  { glyph: "🦉", name: "owl", keywords: ["owl", "night"] },
  { glyph: "🦤", name: "dodo", keywords: ["dodo"] },
  { glyph: "🪶", name: "feather", keywords: ["feather"] },
  { glyph: "🦩", name: "flamingo", keywords: ["flamingo"] },
  { glyph: "🦚", name: "peacock", keywords: ["peacock"] },
  { glyph: "🦜", name: "parrot", keywords: ["parrot"] },
  { glyph: "🪽", name: "wing", keywords: ["wing"] },
  { glyph: "🪿", name: "goose", keywords: ["goose"] },
  { glyph: "🐸", name: "frog", keywords: ["frog"] },
  { glyph: "🐊", name: "crocodile", keywords: ["crocodile", "alligator"] },
  { glyph: "🐢", name: "turtle", keywords: ["turtle"] },
  { glyph: "🦎", name: "lizard", keywords: ["lizard"] },
  { glyph: "🐍", name: "snake", keywords: ["snake"] },
  { glyph: "🐲", name: "dragon face", keywords: ["dragon", "face"] },
  { glyph: "🐉", name: "dragon", keywords: ["dragon"] },
  { glyph: "🦕", name: "sauropod", keywords: ["sauropod", "dinosaur"] },
  { glyph: "🦖", name: "T-Rex", keywords: ["trex", "dinosaur", "t-rex"] },
  { glyph: "🐳", name: "spouting whale", keywords: ["spouting", "whale"] },
  { glyph: "🐋", name: "whale", keywords: ["whale"] },
  { glyph: "🐬", name: "dolphin", keywords: ["dolphin"] },
  { glyph: "🫍", name: "orca", keywords: ["orca"] },
  { glyph: "🦭", name: "seal", keywords: ["seal"] },
  { glyph: "🐟", name: "fish", keywords: ["fish"] },
  { glyph: "🐠", name: "tropical fish", keywords: ["tropical", "fish"] },
  { glyph: "🐡", name: "blowfish", keywords: ["blowfish", "puffer", "fish"] },
  { glyph: "🦈", name: "shark", keywords: ["shark"] },
  { glyph: "🐙", name: "octopus", keywords: ["octopus"] },
  { glyph: "🐚", name: "spiral shell", keywords: ["spiral", "shell"] },
  { glyph: "🪸", name: "coral", keywords: ["coral"] },
  { glyph: "🪼", name: "jellyfish", keywords: ["jellyfish"] },
  { glyph: "🦀", name: "crab", keywords: ["crab"] },
  { glyph: "🦞", name: "lobster", keywords: ["lobster"] },
  { glyph: "🦐", name: "shrimp", keywords: ["shrimp", "prawn"] },
  { glyph: "🦑", name: "squid", keywords: ["squid"] },
  { glyph: "🦪", name: "oyster", keywords: ["oyster"] },
  { glyph: "🐌", name: "snail", keywords: ["snail", "slow"] },
  { glyph: "🦋", name: "butterfly", keywords: ["butterfly"] },
  { glyph: "🐛", name: "bug", keywords: ["bug"] },
  { glyph: "🐜", name: "ant", keywords: ["ant", "bug"] },
  { glyph: "🐝", name: "honeybee", keywords: ["honeybee", "bee", "honey"] },
  { glyph: "🪲", name: "beetle", keywords: ["beetle"] },
  { glyph: "🐞", name: "lady beetle", keywords: ["lady", "beetle", "ladybug"] },
  { glyph: "🦗", name: "cricket", keywords: ["cricket"] },
  { glyph: "🪳", name: "cockroach", keywords: ["cockroach", "bug"] },
  { glyph: "🕷️", name: "spider", keywords: ["spider"] },
  { glyph: "🕸️", name: "spider web", keywords: ["spider", "web"] },
  { glyph: "🦂", name: "scorpion", keywords: ["scorpion"] },
  { glyph: "🦟", name: "mosquito", keywords: ["mosquito"] },
  { glyph: "🪰", name: "fly", keywords: ["fly", "bug"] },
  { glyph: "🪱", name: "worm", keywords: ["worm"] },
  { glyph: "🦠", name: "microbe", keywords: ["microbe"] },
  { glyph: "💐", name: "bouquet", keywords: ["bouquet"] },
  { glyph: "🌸", name: "cherry blossom", keywords: ["cherry", "blossom"] },
  { glyph: "💮", name: "white flower", keywords: ["white", "flower"] },
  { glyph: "🪷", name: "lotus", keywords: ["lotus"] },
  { glyph: "🏵️", name: "rosette", keywords: ["rosette"] },
  { glyph: "🌹", name: "rose", keywords: ["rose"] },
  { glyph: "🥀", name: "wilted flower", keywords: ["wilted", "flower"] },
  { glyph: "🌺", name: "hibiscus", keywords: ["hibiscus"] },
  { glyph: "🌻", name: "sunflower", keywords: ["sunflower"] },
  { glyph: "🌼", name: "blossom", keywords: ["blossom"] },
  { glyph: "🌷", name: "tulip", keywords: ["tulip"] },
  { glyph: "🪻", name: "hyacinth", keywords: ["hyacinth"] },
  { glyph: "🌱", name: "seedling", keywords: ["seedling"] },
  { glyph: "🪴", name: "potted plant", keywords: ["potted", "plant"] },
  { glyph: "🌲", name: "evergreen tree", keywords: ["evergreen", "tree", "pine", "forest"] },
  { glyph: "🌳", name: "deciduous tree", keywords: ["deciduous", "tree", "forest"] },
  { glyph: "🌴", name: "palm tree", keywords: ["palm", "tree", "tropical", "beach"] },
  { glyph: "🌵", name: "cactus", keywords: ["cactus"] },
  { glyph: "🌾", name: "sheaf of rice", keywords: ["sheaf", "rice"] },
  { glyph: "🌿", name: "herb", keywords: ["herb"] },
  { glyph: "☘️", name: "shamrock", keywords: ["shamrock"] },
  { glyph: "🍀", name: "four leaf clover", keywords: ["four", "leaf", "clover"] },
  { glyph: "🍁", name: "maple leaf", keywords: ["maple", "leaf"] },
  { glyph: "🍂", name: "fallen leaf", keywords: ["fallen", "leaf"] },
  { glyph: "🍃", name: "leaf fluttering in wind", keywords: ["leaf", "fluttering", "wind"] },
  { glyph: "🪹", name: "empty nest", keywords: ["empty", "nest"] },
  { glyph: "🪺", name: "nest with eggs", keywords: ["nest", "eggs"] },
  { glyph: "🍄", name: "mushroom", keywords: ["mushroom"] },
  { glyph: "🪾", name: "leafless tree", keywords: ["leafless", "tree"] },
  { glyph: "🍇", name: "grapes", keywords: ["grapes"] },
  { glyph: "🍈", name: "melon", keywords: ["melon"] },
  { glyph: "🍉", name: "watermelon", keywords: ["watermelon"] },
  { glyph: "🍊", name: "tangerine", keywords: ["tangerine", "orange"] },
  { glyph: "🍋", name: "lemon", keywords: ["lemon"] },
  { glyph: "🍌", name: "banana", keywords: ["banana"] },
  { glyph: "🍍", name: "pineapple", keywords: ["pineapple"] },
  { glyph: "🥭", name: "mango", keywords: ["mango"] },
  { glyph: "🍎", name: "red apple", keywords: ["red", "apple"] },
  { glyph: "🍏", name: "green apple", keywords: ["green", "apple"] },
  { glyph: "🍐", name: "pear", keywords: ["pear"] },
  { glyph: "🍑", name: "peach", keywords: ["peach"] },
  { glyph: "🍒", name: "cherries", keywords: ["cherries", "cherry"] },
  { glyph: "🍓", name: "strawberry", keywords: ["strawberry"] },
  { glyph: "🫐", name: "blueberries", keywords: ["blueberries", "blueberry", "berries"] },
  { glyph: "🥝", name: "kiwi fruit", keywords: ["kiwi", "fruit"] },
  { glyph: "🍅", name: "tomato", keywords: ["tomato"] },
  { glyph: "🫒", name: "olive", keywords: ["olive"] },
  { glyph: "🥥", name: "coconut", keywords: ["coconut"] },
  { glyph: "🥑", name: "avocado", keywords: ["avocado"] },
  { glyph: "🍆", name: "eggplant", keywords: ["eggplant"] },
  { glyph: "🥔", name: "potato", keywords: ["potato"] },
  { glyph: "🥕", name: "carrot", keywords: ["carrot"] },
  { glyph: "🌽", name: "ear of corn", keywords: ["ear", "corn"] },
  { glyph: "🌶️", name: "hot pepper", keywords: ["hot", "pepper", "chili", "spicy"] },
  { glyph: "🫑", name: "bell pepper", keywords: ["bell", "pepper"] },
  { glyph: "🥒", name: "cucumber", keywords: ["cucumber"] },
  { glyph: "🥬", name: "leafy green", keywords: ["leafy", "green", "lettuce", "greens"] },
  { glyph: "🥦", name: "broccoli", keywords: ["broccoli"] },
  { glyph: "🧄", name: "garlic", keywords: ["garlic"] },
  { glyph: "🧅", name: "onion", keywords: ["onion"] },
  { glyph: "🥜", name: "peanuts", keywords: ["peanuts", "peanut", "nuts"] },
  { glyph: "🫘", name: "beans", keywords: ["beans"] },
  { glyph: "🌰", name: "chestnut", keywords: ["chestnut"] },
  { glyph: "🫚", name: "ginger root", keywords: ["ginger", "root"] },
  { glyph: "🫛", name: "pea pod", keywords: ["pea", "pod"] },
  { glyph: "🫜", name: "root vegetable", keywords: ["root", "vegetable"] },
  { glyph: "🍞", name: "bread", keywords: ["bread", "toast"] },
  { glyph: "🥐", name: "croissant", keywords: ["croissant", "bread"] },
  { glyph: "🥖", name: "baguette bread", keywords: ["baguette", "bread"] },
  { glyph: "🫓", name: "flatbread", keywords: ["flatbread", "bread"] },
  { glyph: "🥨", name: "pretzel", keywords: ["pretzel"] },
  { glyph: "🥯", name: "bagel", keywords: ["bagel", "bread"] },
  { glyph: "🥞", name: "pancakes", keywords: ["pancakes", "pancake", "breakfast"] },
  { glyph: "🧇", name: "waffle", keywords: ["waffle", "breakfast"] },
  { glyph: "🧀", name: "cheese wedge", keywords: ["cheese", "wedge"] },
  { glyph: "🍖", name: "meat on bone", keywords: ["meat", "bone", "bbq"] },
  {
    glyph: "🍗",
    name: "poultry leg",
    keywords: ["poultry", "leg", "chicken", "drumstick", "meat"],
  },
  { glyph: "🥩", name: "cut of meat", keywords: ["cut", "meat", "steak"] },
  { glyph: "🥓", name: "bacon", keywords: ["bacon"] },
  { glyph: "🍔", name: "hamburger", keywords: ["hamburger", "burger"] },
  { glyph: "🍟", name: "french fries", keywords: ["french", "fries"] },
  { glyph: "🍕", name: "pizza", keywords: ["pizza"] },
  { glyph: "🌭", name: "hot dog", keywords: ["hot", "dog", "hotdog", "hot dog"] },
  { glyph: "🥪", name: "sandwich", keywords: ["sandwich"] },
  { glyph: "🌮", name: "taco", keywords: ["taco"] },
  { glyph: "🌯", name: "burrito", keywords: ["burrito", "wrap"] },
  { glyph: "🫔", name: "tamale", keywords: ["tamale"] },
  {
    glyph: "🥙",
    name: "stuffed flatbread",
    keywords: ["stuffed", "flatbread", "wrap", "gyro", "sandwich"],
  },
  { glyph: "🧆", name: "falafel", keywords: ["falafel"] },
  { glyph: "🥚", name: "egg", keywords: ["egg"] },
  { glyph: "🍳", name: "cooking", keywords: ["cooking", "egg", "fry", "breakfast", "cook"] },
  { glyph: "🥘", name: "shallow pan of food", keywords: ["shallow", "pan", "food"] },
  { glyph: "🍲", name: "pot of food", keywords: ["pot", "food", "stew", "soup"] },
  { glyph: "🫕", name: "fondue", keywords: ["fondue"] },
  { glyph: "🥣", name: "bowl with spoon", keywords: ["bowl", "spoon"] },
  { glyph: "🥗", name: "green salad", keywords: ["green", "salad"] },
  { glyph: "🍿", name: "popcorn", keywords: ["popcorn"] },
  { glyph: "🧈", name: "butter", keywords: ["butter"] },
  { glyph: "🧂", name: "salt", keywords: ["salt"] },
  { glyph: "🥫", name: "canned food", keywords: ["canned", "food"] },
  { glyph: "🍱", name: "bento box", keywords: ["bento", "box", "lunch"] },
  { glyph: "🍘", name: "rice cracker", keywords: ["rice", "cracker"] },
  { glyph: "🍙", name: "rice ball", keywords: ["rice", "ball", "onigiri"] },
  { glyph: "🍚", name: "cooked rice", keywords: ["cooked", "rice"] },
  { glyph: "🍛", name: "curry rice", keywords: ["curry", "rice"] },
  {
    glyph: "🍜",
    name: "steaming bowl",
    keywords: ["steaming", "bowl", "noodles", "ramen", "soup"],
  },
  { glyph: "🍝", name: "spaghetti", keywords: ["spaghetti"] },
  { glyph: "🍠", name: "roasted sweet potato", keywords: ["roasted", "sweet", "potato"] },
  { glyph: "🍢", name: "oden", keywords: ["oden"] },
  { glyph: "🍣", name: "sushi", keywords: ["sushi"] },
  { glyph: "🍤", name: "fried shrimp", keywords: ["fried", "shrimp", "prawn"] },
  { glyph: "🍥", name: "fish cake with swirl", keywords: ["fish", "cake", "swirl", "naruto"] },
  { glyph: "🥮", name: "moon cake", keywords: ["moon", "cake"] },
  { glyph: "🍡", name: "dango", keywords: ["dango"] },
  { glyph: "🥟", name: "dumpling", keywords: ["dumpling"] },
  { glyph: "🥠", name: "fortune cookie", keywords: ["fortune", "cookie"] },
  { glyph: "🥡", name: "takeout box", keywords: ["takeout", "box", "chinese", "food"] },
  { glyph: "🍦", name: "soft ice cream", keywords: ["soft", "ice", "cream"] },
  { glyph: "🍧", name: "shaved ice", keywords: ["shaved", "ice"] },
  { glyph: "🍨", name: "ice cream", keywords: ["ice", "cream"] },
  { glyph: "🍩", name: "doughnut", keywords: ["doughnut", "donut"] },
  { glyph: "🍪", name: "cookie", keywords: ["cookie"] },
  { glyph: "🎂", name: "birthday cake", keywords: ["birthday", "cake"] },
  { glyph: "🍰", name: "shortcake", keywords: ["shortcake", "cake", "dessert"] },
  { glyph: "🧁", name: "cupcake", keywords: ["cupcake", "dessert"] },
  { glyph: "🥧", name: "pie", keywords: ["pie"] },
  { glyph: "🍫", name: "chocolate bar", keywords: ["chocolate", "bar"] },
  { glyph: "🍬", name: "candy", keywords: ["candy"] },
  { glyph: "🍭", name: "lollipop", keywords: ["lollipop", "candy"] },
  { glyph: "🍮", name: "custard", keywords: ["custard", "pudding"] },
  { glyph: "🍯", name: "honey pot", keywords: ["honey", "pot"] },
  { glyph: "🍼", name: "baby bottle", keywords: ["baby", "bottle", "milk"] },
  { glyph: "🥛", name: "glass of milk", keywords: ["glass", "milk"] },
  { glyph: "☕", name: "hot beverage", keywords: ["hot", "beverage", "coffee", "tea"] },
  { glyph: "🫖", name: "teapot", keywords: ["teapot", "tea"] },
  {
    glyph: "🍵",
    name: "teacup without handle",
    keywords: ["teacup", "without", "handle", "tea", "green", "matcha"],
  },
  { glyph: "🍶", name: "sake", keywords: ["sake"] },
  {
    glyph: "🍾",
    name: "bottle with popping cork",
    keywords: ["bottle", "popping", "cork", "champagne", "celebrate"],
  },
  { glyph: "🍷", name: "wine glass", keywords: ["wine", "glass"] },
  { glyph: "🍸", name: "cocktail glass", keywords: ["cocktail", "glass", "drink", "martini"] },
  { glyph: "🍹", name: "tropical drink", keywords: ["tropical", "drink", "cocktail"] },
  { glyph: "🍺", name: "beer mug", keywords: ["beer", "mug"] },
  {
    glyph: "🍻",
    name: "clinking beer mugs",
    keywords: ["clinking", "beer", "mugs", "cheers", "toast"],
  },
  {
    glyph: "🥂",
    name: "clinking glasses",
    keywords: ["clinking", "glasses", "cheers", "toast", "celebrate"],
  },
  {
    glyph: "🥃",
    name: "tumbler glass",
    keywords: ["tumbler", "glass", "whiskey", "whisky", "drink"],
  },
  { glyph: "🫗", name: "pouring liquid", keywords: ["pouring", "liquid"] },
  { glyph: "🥤", name: "cup with straw", keywords: ["cup", "straw", "drink", "soda"] },
  { glyph: "🧋", name: "bubble tea", keywords: ["bubble", "tea"] },
  { glyph: "🧃", name: "beverage box", keywords: ["beverage", "box", "juice", "drink"] },
  { glyph: "🧉", name: "mate", keywords: ["mate"] },
  { glyph: "🧊", name: "ice", keywords: ["ice"] },
  { glyph: "🥢", name: "chopsticks", keywords: ["chopsticks"] },
  {
    glyph: "🍽️",
    name: "fork and knife with plate",
    keywords: ["fork", "knife", "plate", "dinner", "meal"],
  },
  { glyph: "🍴", name: "fork and knife", keywords: ["fork", "knife", "eat"] },
  { glyph: "🥄", name: "spoon", keywords: ["spoon"] },
  { glyph: "🔪", name: "kitchen knife", keywords: ["kitchen", "knife", "cut", "cook"] },
  { glyph: "🫙", name: "jar", keywords: ["jar"] },
  { glyph: "🏺", name: "amphora", keywords: ["amphora", "vase"] },
  { glyph: "🎃", name: "jack-o-lantern", keywords: ["jackolantern"] },
  { glyph: "🎄", name: "Christmas tree", keywords: ["christmas", "tree"] },
  { glyph: "🎆", name: "fireworks", keywords: ["fireworks"] },
  { glyph: "🎇", name: "sparkler", keywords: ["sparkler"] },
  { glyph: "🧨", name: "firecracker", keywords: ["firecracker"] },
  { glyph: "✨", name: "sparkles", keywords: ["sparkles", "sparkle", "shiny", "magic"] },
  { glyph: "🎈", name: "balloon", keywords: ["balloon", "party"] },
  { glyph: "🎉", name: "party popper", keywords: ["party", "popper", "celebrate", "tada"] },
  { glyph: "🎊", name: "confetti ball", keywords: ["confetti", "ball", "party", "celebrate"] },
  { glyph: "🎋", name: "tanabata tree", keywords: ["tanabata", "tree"] },
  { glyph: "🎍", name: "pine decoration", keywords: ["pine", "decoration"] },
  { glyph: "🎎", name: "Japanese dolls", keywords: ["japanese", "dolls"] },
  { glyph: "🎏", name: "carp streamer", keywords: ["carp", "streamer"] },
  { glyph: "🎐", name: "wind chime", keywords: ["wind", "chime"] },
  { glyph: "🎑", name: "moon viewing ceremony", keywords: ["moon", "viewing", "ceremony"] },
  { glyph: "🧧", name: "red envelope", keywords: ["red", "envelope"] },
  { glyph: "🎀", name: "ribbon", keywords: ["ribbon"] },
  { glyph: "🎁", name: "wrapped gift", keywords: ["wrapped", "gift", "present"] },
  { glyph: "🎗️", name: "reminder ribbon", keywords: ["reminder", "ribbon"] },
  { glyph: "🎟️", name: "admission tickets", keywords: ["admission", "tickets", "ticket"] },
  { glyph: "🎫", name: "ticket", keywords: ["ticket"] },
  { glyph: "🎖️", name: "military medal", keywords: ["military", "medal"] },
  { glyph: "🏆", name: "trophy", keywords: ["trophy", "win", "champion"] },
  { glyph: "🏅", name: "sports medal", keywords: ["sports", "medal", "award"] },
  { glyph: "🥇", name: "1st place medal", keywords: ["1st", "place", "medal", "gold", "first"] },
  { glyph: "🥈", name: "2nd place medal", keywords: ["2nd", "place", "medal", "silver", "second"] },
  { glyph: "🥉", name: "3rd place medal", keywords: ["3rd", "place", "medal", "bronze", "third"] },
  { glyph: "⚽", name: "soccer ball", keywords: ["soccer", "ball", "football"] },
  { glyph: "⚾", name: "baseball", keywords: ["baseball"] },
  { glyph: "🥎", name: "softball", keywords: ["softball"] },
  { glyph: "🏀", name: "basketball", keywords: ["basketball"] },
  { glyph: "🏐", name: "volleyball", keywords: ["volleyball", "ball"] },
  { glyph: "🏈", name: "american football", keywords: ["american", "football"] },
  { glyph: "🏉", name: "rugby football", keywords: ["rugby", "football"] },
  { glyph: "🎾", name: "tennis", keywords: ["tennis", "ball"] },
  { glyph: "🥏", name: "flying disc", keywords: ["flying", "disc"] },
  { glyph: "🎳", name: "bowling", keywords: ["bowling"] },
  { glyph: "🏏", name: "cricket game", keywords: ["cricket", "game"] },
  { glyph: "🏑", name: "field hockey", keywords: ["field", "hockey"] },
  { glyph: "🏒", name: "ice hockey", keywords: ["ice", "hockey"] },
  { glyph: "🥍", name: "lacrosse", keywords: ["lacrosse"] },
  { glyph: "🏓", name: "ping pong", keywords: ["ping", "pong", "table", "tennis"] },
  { glyph: "🏸", name: "badminton", keywords: ["badminton"] },
  { glyph: "🥊", name: "boxing glove", keywords: ["boxing", "glove", "punch"] },
  { glyph: "🥋", name: "martial arts uniform", keywords: ["martial", "arts", "uniform", "karate"] },
  { glyph: "🥅", name: "goal net", keywords: ["goal", "net"] },
  { glyph: "⛳", name: "flag in hole", keywords: ["flag", "hole", "golf"] },
  { glyph: "⛸️", name: "ice skate", keywords: ["ice", "skate"] },
  { glyph: "🎣", name: "fishing pole", keywords: ["fishing", "pole", "fish", "rod"] },
  { glyph: "🤿", name: "diving mask", keywords: ["diving", "mask", "snorkel", "scuba"] },
  { glyph: "🎽", name: "running shirt", keywords: ["running", "shirt"] },
  { glyph: "🎿", name: "skis", keywords: ["skis", "ski", "skiing", "snow"] },
  { glyph: "🛷", name: "sled", keywords: ["sled", "sledge"] },
  { glyph: "🥌", name: "curling stone", keywords: ["curling", "stone"] },
  { glyph: "🎯", name: "bullseye", keywords: ["bullseye", "target", "goal"] },
  { glyph: "🪀", name: "yo-yo", keywords: ["yoyo"] },
  { glyph: "🪁", name: "kite", keywords: ["kite"] },
  { glyph: "🔫", name: "water pistol", keywords: ["water", "pistol"] },
  { glyph: "🎱", name: "pool 8 ball", keywords: ["pool", "ball", "billiards", "8"] },
  { glyph: "🔮", name: "crystal ball", keywords: ["crystal", "ball"] },
  { glyph: "🪄", name: "magic wand", keywords: ["magic", "wand"] },
  { glyph: "🎮", name: "video game", keywords: ["video", "game", "gaming", "controller", "play"] },
  { glyph: "🕹️", name: "joystick", keywords: ["joystick", "game", "controller", "arcade"] },
  { glyph: "🎰", name: "slot machine", keywords: ["slot", "machine"] },
  { glyph: "🎲", name: "game die", keywords: ["game", "die"] },
  { glyph: "🧩", name: "puzzle piece", keywords: ["puzzle", "piece"] },
  { glyph: "🧸", name: "teddy bear", keywords: ["teddy", "bear"] },
  { glyph: "🪅", name: "piñata", keywords: ["piata"] },
  { glyph: "🪩", name: "mirror ball", keywords: ["mirror", "ball"] },
  { glyph: "🪆", name: "nesting dolls", keywords: ["nesting", "dolls"] },
  { glyph: "♠️", name: "spade suit", keywords: ["spade", "suit"] },
  { glyph: "♥️", name: "heart suit", keywords: ["heart", "suit"] },
  { glyph: "♦️", name: "diamond suit", keywords: ["diamond", "suit"] },
  { glyph: "♣️", name: "club suit", keywords: ["club", "suit"] },
  { glyph: "♟️", name: "chess pawn", keywords: ["chess", "pawn"] },
  { glyph: "🃏", name: "joker", keywords: ["joker"] },
  { glyph: "🀄", name: "mahjong red dragon", keywords: ["mahjong", "red", "dragon"] },
  { glyph: "🎴", name: "flower playing cards", keywords: ["flower", "playing", "cards"] },
  {
    glyph: "🎭",
    name: "performing arts",
    keywords: ["performing", "arts", "theater", "theatre", "drama", "mask"],
  },
  { glyph: "🖼️", name: "framed picture", keywords: ["framed", "picture"] },
  { glyph: "🎨", name: "artist palette", keywords: ["artist", "palette", "art", "paint"] },
  { glyph: "🧵", name: "thread", keywords: ["thread"] },
  { glyph: "🪡", name: "sewing needle", keywords: ["sewing", "needle"] },
  { glyph: "🧶", name: "yarn", keywords: ["yarn"] },
  { glyph: "🪢", name: "knot", keywords: ["knot"] },
  {
    glyph: "🏁",
    name: "chequered flag",
    keywords: ["chequered", "flag", "checkered", "finish", "race"],
  },
  { glyph: "🚩", name: "triangular flag", keywords: ["triangular", "flag", "red"] },
  { glyph: "🎌", name: "crossed flags", keywords: ["crossed", "flags", "flag", "japan"] },
  { glyph: "🏴", name: "black flag", keywords: ["black", "flag"] },
  { glyph: "🏳️", name: "white flag", keywords: ["white", "flag"] },
  {
    glyph: "🌍",
    name: "globe showing Europe-Africa",
    keywords: ["globe", "showing", "europeafrica"],
  },
  { glyph: "🌎", name: "globe showing Americas", keywords: ["globe", "showing", "americas"] },
  {
    glyph: "🌏",
    name: "globe showing Asia-Australia",
    keywords: ["globe", "showing", "asiaaustralia"],
  },
  { glyph: "🌐", name: "globe with meridians", keywords: ["globe", "meridians"] },
  { glyph: "🗺️", name: "world map", keywords: ["world", "map"] },
  { glyph: "🗾", name: "map of Japan", keywords: ["map", "japan"] },
  { glyph: "🧭", name: "compass", keywords: ["compass"] },
  { glyph: "🏔️", name: "snow-capped mountain", keywords: ["snowcapped", "mountain", "snow"] },
  { glyph: "⛰️", name: "mountain", keywords: ["mountain"] },
  { glyph: "🛘", name: "landslide", keywords: ["landslide"] },
  { glyph: "🌋", name: "volcano", keywords: ["volcano"] },
  { glyph: "🗻", name: "mount fuji", keywords: ["mount", "fuji", "mountain"] },
  { glyph: "🏕️", name: "camping", keywords: ["camping"] },
  { glyph: "🏖️", name: "beach with umbrella", keywords: ["beach", "umbrella"] },
  { glyph: "🏜️", name: "desert", keywords: ["desert"] },
  { glyph: "🏝️", name: "desert island", keywords: ["desert", "island"] },
  { glyph: "🏞️", name: "national park", keywords: ["national", "park"] },
  { glyph: "🏟️", name: "stadium", keywords: ["stadium"] },
  { glyph: "🏛️", name: "classical building", keywords: ["classical", "building"] },
  { glyph: "🏗️", name: "building construction", keywords: ["building", "construction"] },
  { glyph: "🧱", name: "brick", keywords: ["brick"] },
  { glyph: "🪨", name: "rock", keywords: ["rock"] },
  { glyph: "🪵", name: "wood", keywords: ["wood"] },
  { glyph: "🛖", name: "hut", keywords: ["hut", "igloo"] },
  { glyph: "🏘️", name: "houses", keywords: ["houses"] },
  { glyph: "🏚️", name: "derelict house", keywords: ["derelict", "house"] },
  { glyph: "🏠", name: "house", keywords: ["house"] },
  { glyph: "🏡", name: "house with garden", keywords: ["house", "garden", "home"] },
  { glyph: "🏢", name: "office building", keywords: ["office", "building"] },
  { glyph: "🏣", name: "Japanese post office", keywords: ["japanese", "post", "office"] },
  { glyph: "🏤", name: "post office", keywords: ["post", "office"] },
  { glyph: "🏥", name: "hospital", keywords: ["hospital"] },
  { glyph: "🏦", name: "bank", keywords: ["bank"] },
  { glyph: "🏨", name: "hotel", keywords: ["hotel"] },
  { glyph: "🏩", name: "love hotel", keywords: ["love", "hotel"] },
  { glyph: "🏪", name: "convenience store", keywords: ["convenience", "store", "shop"] },
  { glyph: "🏫", name: "school", keywords: ["school"] },
  { glyph: "🏬", name: "department store", keywords: ["department", "store", "mall", "building"] },
  { glyph: "🏭", name: "factory", keywords: ["factory"] },
  { glyph: "🏯", name: "Japanese castle", keywords: ["japanese", "castle"] },
  { glyph: "🏰", name: "castle", keywords: ["castle"] },
  { glyph: "💒", name: "wedding", keywords: ["wedding"] },
  { glyph: "🗼", name: "Tokyo tower", keywords: ["tokyo", "tower"] },
  { glyph: "🗽", name: "Statue of Liberty", keywords: ["statue", "liberty"] },
  { glyph: "⛪", name: "church", keywords: ["church"] },
  { glyph: "🕌", name: "mosque", keywords: ["mosque"] },
  { glyph: "🛕", name: "hindu temple", keywords: ["hindu", "temple"] },
  { glyph: "🕍", name: "synagogue", keywords: ["synagogue"] },
  { glyph: "⛩️", name: "shinto shrine", keywords: ["shinto", "shrine", "japanese"] },
  { glyph: "🕋", name: "kaaba", keywords: ["kaaba", "mecca"] },
  { glyph: "⛲", name: "fountain", keywords: ["fountain"] },
  { glyph: "⛺", name: "tent", keywords: ["tent", "camp", "camping"] },
  { glyph: "🌁", name: "foggy", keywords: ["foggy", "fog", "bridge"] },
  { glyph: "🌃", name: "night with stars", keywords: ["night", "stars", "city"] },
  { glyph: "🏙️", name: "cityscape", keywords: ["cityscape"] },
  {
    glyph: "🌄",
    name: "sunrise over mountains",
    keywords: ["sunrise", "over", "mountains", "mountain"],
  },
  { glyph: "🌅", name: "sunrise", keywords: ["sunrise", "sun"] },
  { glyph: "🌆", name: "cityscape at dusk", keywords: ["cityscape", "dusk", "city", "skyline"] },
  { glyph: "🌇", name: "sunset", keywords: ["sunset", "city", "evening"] },
  { glyph: "🌉", name: "bridge at night", keywords: ["bridge", "night"] },
  { glyph: "♨️", name: "hot springs", keywords: ["hot", "springs"] },
  { glyph: "🎠", name: "carousel horse", keywords: ["carousel", "horse", "merry"] },
  { glyph: "🛝", name: "playground slide", keywords: ["playground", "slide"] },
  { glyph: "🎡", name: "ferris wheel", keywords: ["ferris", "wheel", "fair"] },
  { glyph: "🎢", name: "roller coaster", keywords: ["roller", "coaster", "amusement"] },
  { glyph: "💈", name: "barber pole", keywords: ["barber", "pole"] },
  { glyph: "🎪", name: "circus tent", keywords: ["circus", "tent"] },
  { glyph: "🚂", name: "locomotive", keywords: ["locomotive", "train"] },
  { glyph: "🚃", name: "railway car", keywords: ["railway", "car", "train", "tram"] },
  { glyph: "🚄", name: "high-speed train", keywords: ["highspeed", "train"] },
  { glyph: "🚅", name: "bullet train", keywords: ["bullet", "train"] },
  { glyph: "🚆", name: "train", keywords: ["train"] },
  { glyph: "🚇", name: "metro", keywords: ["metro", "subway", "train", "underground"] },
  { glyph: "🚈", name: "light rail", keywords: ["light", "rail", "train"] },
  { glyph: "🚉", name: "station", keywords: ["station"] },
  { glyph: "🚊", name: "tram", keywords: ["tram"] },
  { glyph: "🚝", name: "monorail", keywords: ["monorail", "train"] },
  { glyph: "🚞", name: "mountain railway", keywords: ["mountain", "railway", "train"] },
  { glyph: "🚋", name: "tram car", keywords: ["tram", "car", "train"] },
  { glyph: "🚌", name: "bus", keywords: ["bus"] },
  { glyph: "🚍", name: "oncoming bus", keywords: ["oncoming", "bus"] },
  { glyph: "🚎", name: "trolleybus", keywords: ["trolleybus", "bus", "trolley"] },
  { glyph: "🚐", name: "minibus", keywords: ["minibus", "van"] },
  { glyph: "🚑", name: "ambulance", keywords: ["ambulance", "emergency"] },
  { glyph: "🚒", name: "fire engine", keywords: ["fire", "engine", "firetruck", "emergency"] },
  { glyph: "🚓", name: "police car", keywords: ["police", "car", "cop"] },
  { glyph: "🚔", name: "oncoming police car", keywords: ["oncoming", "police", "car", "cop"] },
  { glyph: "🚕", name: "taxi", keywords: ["taxi", "cab"] },
  { glyph: "🚖", name: "oncoming taxi", keywords: ["oncoming", "taxi"] },
  { glyph: "🚗", name: "automobile", keywords: ["automobile", "car", "auto", "vehicle"] },
  { glyph: "🚘", name: "oncoming automobile", keywords: ["oncoming", "automobile"] },
  {
    glyph: "🚙",
    name: "sport utility vehicle",
    keywords: ["sport", "utility", "vehicle", "car", "suv"],
  },
  { glyph: "🛻", name: "pickup truck", keywords: ["pickup", "truck"] },
  { glyph: "🚚", name: "delivery truck", keywords: ["delivery", "truck"] },
  { glyph: "🚛", name: "articulated lorry", keywords: ["articulated", "lorry", "truck"] },
  { glyph: "🚜", name: "tractor", keywords: ["tractor", "farm"] },
  { glyph: "🏎️", name: "racing car", keywords: ["racing", "car", "race"] },
  { glyph: "🏍️", name: "motorcycle", keywords: ["motorcycle", "bike"] },
  { glyph: "🛵", name: "motor scooter", keywords: ["motor", "scooter", "bike"] },
  { glyph: "🦽", name: "manual wheelchair", keywords: ["manual", "wheelchair"] },
  { glyph: "🦼", name: "motorized wheelchair", keywords: ["motorized", "wheelchair"] },
  { glyph: "🛺", name: "auto rickshaw", keywords: ["auto", "rickshaw"] },
  { glyph: "🚲", name: "bicycle", keywords: ["bicycle", "bike", "cycle"] },
  { glyph: "🛴", name: "kick scooter", keywords: ["kick", "scooter"] },
  { glyph: "🛹", name: "skateboard", keywords: ["skateboard"] },
  { glyph: "🛼", name: "roller skate", keywords: ["roller", "skate"] },
  { glyph: "🚏", name: "bus stop", keywords: ["bus", "stop"] },
  { glyph: "🛣️", name: "motorway", keywords: ["motorway", "highway", "road"] },
  { glyph: "🛤️", name: "railway track", keywords: ["railway", "track", "train"] },
  { glyph: "🛢️", name: "oil drum", keywords: ["oil", "drum", "barrel"] },
  { glyph: "⛽", name: "fuel pump", keywords: ["fuel", "pump", "gas", "station", "petrol"] },
  { glyph: "🛞", name: "wheel", keywords: ["wheel"] },
  { glyph: "🚨", name: "police car light", keywords: ["police", "car", "light"] },
  { glyph: "🚥", name: "horizontal traffic light", keywords: ["horizontal", "traffic", "light"] },
  { glyph: "🚦", name: "vertical traffic light", keywords: ["vertical", "traffic", "light"] },
  { glyph: "🛑", name: "stop sign", keywords: ["stop", "sign"] },
  { glyph: "🚧", name: "construction", keywords: ["construction", "roadwork"] },
  { glyph: "⚓", name: "anchor", keywords: ["anchor"] },
  { glyph: "🛟", name: "ring buoy", keywords: ["ring", "buoy"] },
  { glyph: "⛵", name: "sailboat", keywords: ["sailboat", "boat", "sail", "sailing"] },
  { glyph: "🛶", name: "canoe", keywords: ["canoe"] },
  { glyph: "🚤", name: "speedboat", keywords: ["speedboat", "boat"] },
  { glyph: "🛳️", name: "passenger ship", keywords: ["passenger", "ship"] },
  { glyph: "⛴️", name: "ferry", keywords: ["ferry"] },
  { glyph: "🛥️", name: "motor boat", keywords: ["motor", "boat", "yacht"] },
  { glyph: "🚢", name: "ship", keywords: ["ship", "boat"] },
  { glyph: "✈️", name: "airplane", keywords: ["airplane", "plane", "flight", "airport"] },
  { glyph: "🛩️", name: "small airplane", keywords: ["small", "airplane"] },
  {
    glyph: "🛫",
    name: "airplane departure",
    keywords: ["airplane", "departure", "plane", "takeoff", "flight"],
  },
  {
    glyph: "🛬",
    name: "airplane arrival",
    keywords: ["airplane", "arrival", "plane", "landing", "flight"],
  },
  { glyph: "🪂", name: "parachute", keywords: ["parachute"] },
  { glyph: "💺", name: "seat", keywords: ["seat"] },
  { glyph: "🚁", name: "helicopter", keywords: ["helicopter"] },
  { glyph: "🚟", name: "suspension railway", keywords: ["suspension", "railway", "train"] },
  {
    glyph: "🚠",
    name: "mountain cableway",
    keywords: ["mountain", "cableway", "cable", "car", "gondola"],
  },
  { glyph: "🚡", name: "aerial tramway", keywords: ["aerial", "tramway", "cable", "car", "tram"] },
  { glyph: "🛰️", name: "satellite", keywords: ["satellite", "space"] },
  { glyph: "🚀", name: "rocket", keywords: ["rocket", "space", "launch"] },
  { glyph: "🛸", name: "flying saucer", keywords: ["flying", "saucer", "ufo", "space", "alien"] },
  { glyph: "🛎️", name: "bellhop bell", keywords: ["bellhop", "bell"] },
  { glyph: "🧳", name: "luggage", keywords: ["luggage"] },
  { glyph: "⌛", name: "hourglass done", keywords: ["hourglass", "done"] },
  { glyph: "⏳", name: "hourglass not done", keywords: ["hourglass", "not", "done"] },
  { glyph: "⌚", name: "watch", keywords: ["watch"] },
  { glyph: "⏰", name: "alarm clock", keywords: ["alarm", "clock"] },
  { glyph: "⏱️", name: "stopwatch", keywords: ["stopwatch"] },
  { glyph: "⏲️", name: "timer clock", keywords: ["timer", "clock"] },
  { glyph: "🕰️", name: "mantelpiece clock", keywords: ["mantelpiece", "clock"] },
  { glyph: "🕛", name: "twelve o’clock", keywords: ["twelve", "oclock"] },
  { glyph: "🕧", name: "twelve-thirty", keywords: ["twelvethirty"] },
  { glyph: "🕐", name: "one o’clock", keywords: ["one", "oclock"] },
  { glyph: "🕜", name: "one-thirty", keywords: ["onethirty"] },
  { glyph: "🕑", name: "two o’clock", keywords: ["two", "oclock"] },
  { glyph: "🕝", name: "two-thirty", keywords: ["twothirty"] },
  { glyph: "🕒", name: "three o’clock", keywords: ["three", "oclock"] },
  { glyph: "🕞", name: "three-thirty", keywords: ["threethirty"] },
  { glyph: "🕓", name: "four o’clock", keywords: ["four", "oclock"] },
  { glyph: "🕟", name: "four-thirty", keywords: ["fourthirty"] },
  { glyph: "🕔", name: "five o’clock", keywords: ["five", "oclock"] },
  { glyph: "🕠", name: "five-thirty", keywords: ["fivethirty"] },
  { glyph: "🕕", name: "six o’clock", keywords: ["six", "oclock"] },
  { glyph: "🕡", name: "six-thirty", keywords: ["sixthirty"] },
  { glyph: "🕖", name: "seven o’clock", keywords: ["seven", "oclock"] },
  { glyph: "🕢", name: "seven-thirty", keywords: ["seventhirty"] },
  { glyph: "🕗", name: "eight o’clock", keywords: ["eight", "oclock"] },
  { glyph: "🕣", name: "eight-thirty", keywords: ["eightthirty"] },
  { glyph: "🕘", name: "nine o’clock", keywords: ["nine", "oclock"] },
  { glyph: "🕤", name: "nine-thirty", keywords: ["ninethirty"] },
  { glyph: "🕙", name: "ten o’clock", keywords: ["ten", "oclock"] },
  { glyph: "🕥", name: "ten-thirty", keywords: ["tenthirty"] },
  { glyph: "🕚", name: "eleven o’clock", keywords: ["eleven", "oclock"] },
  { glyph: "🕦", name: "eleven-thirty", keywords: ["eleventhirty"] },
  { glyph: "🌑", name: "new moon", keywords: ["new", "moon"] },
  { glyph: "🌒", name: "waxing crescent moon", keywords: ["waxing", "crescent", "moon"] },
  { glyph: "🌓", name: "first quarter moon", keywords: ["first", "quarter", "moon"] },
  { glyph: "🌔", name: "waxing gibbous moon", keywords: ["waxing", "gibbous", "moon"] },
  { glyph: "🌕", name: "full moon", keywords: ["full", "moon"] },
  { glyph: "🌖", name: "waning gibbous moon", keywords: ["waning", "gibbous", "moon"] },
  { glyph: "🌗", name: "last quarter moon", keywords: ["last", "quarter", "moon"] },
  { glyph: "🌘", name: "waning crescent moon", keywords: ["waning", "crescent", "moon"] },
  { glyph: "🌙", name: "crescent moon", keywords: ["crescent", "moon", "night"] },
  { glyph: "🌚", name: "new moon face", keywords: ["new", "moon", "face", "night", "dark"] },
  { glyph: "🌛", name: "first quarter moon face", keywords: ["first", "quarter", "moon", "face"] },
  { glyph: "🌜", name: "last quarter moon face", keywords: ["last", "quarter", "moon", "face"] },
  { glyph: "🌡️", name: "thermometer", keywords: ["thermometer"] },
  { glyph: "☀️", name: "sun", keywords: ["sun", "sunny", "warm"] },
  { glyph: "🌝", name: "full moon face", keywords: ["full", "moon", "face", "bright"] },
  { glyph: "🌞", name: "sun with face", keywords: ["sun", "face"] },
  { glyph: "🪐", name: "ringed planet", keywords: ["ringed", "planet"] },
  { glyph: "⭐", name: "star", keywords: ["star"] },
  { glyph: "🌟", name: "glowing star", keywords: ["glowing", "star"] },
  { glyph: "🌠", name: "shooting star", keywords: ["shooting", "star"] },
  { glyph: "🌌", name: "milky way", keywords: ["milky", "way", "space", "galaxy"] },
  { glyph: "☁️", name: "cloud", keywords: ["cloud"] },
  {
    glyph: "⛅",
    name: "sun behind cloud",
    keywords: ["sun", "behind", "cloud", "sunny", "partly"],
  },
  {
    glyph: "⛈️",
    name: "cloud with lightning and rain",
    keywords: ["cloud", "lightning", "rain", "storm", "weather"],
  },
  { glyph: "🌤️", name: "sun behind small cloud", keywords: ["sun", "behind", "small", "cloud"] },
  {
    glyph: "🌥️",
    name: "sun behind large cloud",
    keywords: ["sun", "behind", "large", "cloud", "sunny"],
  },
  {
    glyph: "🌦️",
    name: "sun behind rain cloud",
    keywords: ["sun", "behind", "rain", "cloud", "sunny"],
  },
  { glyph: "🌧️", name: "cloud with rain", keywords: ["cloud", "rain"] },
  { glyph: "🌨️", name: "cloud with snow", keywords: ["cloud", "snow"] },
  { glyph: "🌩️", name: "cloud with lightning", keywords: ["cloud", "lightning", "thunder"] },
  { glyph: "🌪️", name: "tornado", keywords: ["tornado"] },
  { glyph: "🌫️", name: "fog", keywords: ["fog"] },
  { glyph: "🌬️", name: "wind face", keywords: ["wind", "face"] },
  { glyph: "🌀", name: "cyclone", keywords: ["cyclone"] },
  { glyph: "🌈", name: "rainbow", keywords: ["rainbow"] },
  { glyph: "🌂", name: "closed umbrella", keywords: ["closed", "umbrella"] },
  { glyph: "☂️", name: "umbrella", keywords: ["umbrella", "rain"] },
  { glyph: "☔", name: "umbrella with rain drops", keywords: ["umbrella", "rain", "drops", "wet"] },
  { glyph: "⛱️", name: "umbrella on ground", keywords: ["umbrella", "ground"] },
  {
    glyph: "⚡",
    name: "high voltage",
    keywords: ["high", "voltage", "lightning", "power", "energy", "zap"],
  },
  { glyph: "❄️", name: "snowflake", keywords: ["snowflake", "snow", "cold", "winter", "ice"] },
  { glyph: "☃️", name: "snowman", keywords: ["snowman", "snow", "winter"] },
  { glyph: "⛄", name: "snowman without snow", keywords: ["snowman", "without", "snow", "winter"] },
  { glyph: "☄️", name: "comet", keywords: ["comet"] },
  { glyph: "🔥", name: "fire", keywords: ["fire", "hot"] },
  { glyph: "💧", name: "droplet", keywords: ["droplet"] },
  { glyph: "🌊", name: "water wave", keywords: ["water", "wave", "ocean", "sea"] },
  { glyph: "🇦🇨", name: "flag: Ascension Island", keywords: ["flag", "ascension", "island"] },
  { glyph: "🇦🇩", name: "flag: Andorra", keywords: ["flag", "andorra"] },
  {
    glyph: "🇦🇪",
    name: "flag: United Arab Emirates",
    keywords: ["flag", "united", "arab", "emirates", "uae"],
  },
  { glyph: "🇦🇫", name: "flag: Afghanistan", keywords: ["flag", "afghanistan", "afghan"] },
  { glyph: "🇦🇬", name: "flag: Antigua & Barbuda", keywords: ["flag", "antigua", "barbuda"] },
  { glyph: "🇦🇮", name: "flag: Anguilla", keywords: ["flag", "anguilla"] },
  { glyph: "🇦🇱", name: "flag: Albania", keywords: ["flag", "albania", "albanian"] },
  { glyph: "🇦🇲", name: "flag: Armenia", keywords: ["flag", "armenia", "armenian"] },
  { glyph: "🇦🇴", name: "flag: Angola", keywords: ["flag", "angola", "angolan"] },
  { glyph: "🇦🇶", name: "flag: Antarctica", keywords: ["flag", "antarctica"] },
  { glyph: "🇦🇷", name: "flag: Argentina", keywords: ["flag", "argentina", "argentinian"] },
  { glyph: "🇦🇸", name: "flag: American Samoa", keywords: ["flag", "american", "samoa"] },
  { glyph: "🇦🇹", name: "flag: Austria", keywords: ["flag", "austria", "austrian"] },
  { glyph: "🇦🇺", name: "flag: Australia", keywords: ["flag", "australia", "australian"] },
  { glyph: "🇦🇼", name: "flag: Aruba", keywords: ["flag", "aruba"] },
  { glyph: "🇦🇽", name: "flag: Åland Islands", keywords: ["flag", "land", "islands", "aland"] },
  { glyph: "🇦🇿", name: "flag: Azerbaijan", keywords: ["flag", "azerbaijan", "azerbaijani"] },
  { glyph: "🇧🇦", name: "flag: Bosnia & Herzegovina", keywords: ["flag", "bosnia", "herzegovina"] },
  { glyph: "🇧🇧", name: "flag: Barbados", keywords: ["flag", "barbados"] },
  { glyph: "🇧🇩", name: "flag: Bangladesh", keywords: ["flag", "bangladesh", "bangladeshi"] },
  { glyph: "🇧🇪", name: "flag: Belgium", keywords: ["flag", "belgium", "belgian"] },
  { glyph: "🇧🇫", name: "flag: Burkina Faso", keywords: ["flag", "burkina", "faso"] },
  { glyph: "🇧🇬", name: "flag: Bulgaria", keywords: ["flag", "bulgaria", "bulgarian"] },
  { glyph: "🇧🇭", name: "flag: Bahrain", keywords: ["flag", "bahrain"] },
  { glyph: "🇧🇮", name: "flag: Burundi", keywords: ["flag", "burundi", "burundian"] },
  { glyph: "🇧🇯", name: "flag: Benin", keywords: ["flag", "benin", "beninese"] },
  { glyph: "🇧🇱", name: "flag: St. Barthélemy", keywords: ["flag", "barthlemy"] },
  { glyph: "🇧🇲", name: "flag: Bermuda", keywords: ["flag", "bermuda"] },
  { glyph: "🇧🇳", name: "flag: Brunei", keywords: ["flag", "brunei"] },
  { glyph: "🇧🇴", name: "flag: Bolivia", keywords: ["flag", "bolivia", "bolivian"] },
  {
    glyph: "🇧🇶",
    name: "flag: Caribbean Netherlands",
    keywords: ["flag", "caribbean", "netherlands"],
  },
  { glyph: "🇧🇷", name: "flag: Brazil", keywords: ["flag", "brazil", "brazilian"] },
  { glyph: "🇧🇸", name: "flag: Bahamas", keywords: ["flag", "bahamas"] },
  { glyph: "🇧🇹", name: "flag: Bhutan", keywords: ["flag", "bhutan"] },
  { glyph: "🇧🇻", name: "flag: Bouvet Island", keywords: ["flag", "bouvet", "island"] },
  { glyph: "🇧🇼", name: "flag: Botswana", keywords: ["flag", "botswana"] },
  { glyph: "🇧🇾", name: "flag: Belarus", keywords: ["flag", "belarus", "belarusian"] },
  { glyph: "🇧🇿", name: "flag: Belize", keywords: ["flag", "belize"] },
  { glyph: "🇨🇦", name: "flag: Canada", keywords: ["flag", "canada", "canadian"] },
  {
    glyph: "🇨🇨",
    name: "flag: Cocos (Keeling) Islands",
    keywords: ["flag", "cocos", "keeling", "islands"],
  },
  { glyph: "🇨🇩", name: "flag: Congo - Kinshasa", keywords: ["flag", "congo", "kinshasa", "drc"] },
  {
    glyph: "🇨🇫",
    name: "flag: Central African Republic",
    keywords: ["flag", "central", "african", "republic"],
  },
  { glyph: "🇨🇬", name: "flag: Congo - Brazzaville", keywords: ["flag", "congo", "brazzaville"] },
  { glyph: "🇨🇭", name: "flag: Switzerland", keywords: ["flag", "switzerland", "swiss"] },
  {
    glyph: "🇨🇮",
    name: "flag: Côte d’Ivoire",
    keywords: ["flag", "cte", "divoire", "ivory", "coast"],
  },
  { glyph: "🇨🇰", name: "flag: Cook Islands", keywords: ["flag", "cook", "islands"] },
  { glyph: "🇨🇱", name: "flag: Chile", keywords: ["flag", "chile", "chilean"] },
  { glyph: "🇨🇲", name: "flag: Cameroon", keywords: ["flag", "cameroon", "cameroonian"] },
  { glyph: "🇨🇳", name: "flag: China", keywords: ["flag", "china", "chinese"] },
  { glyph: "🇨🇴", name: "flag: Colombia", keywords: ["flag", "colombia", "colombian"] },
  { glyph: "🇨🇵", name: "flag: Clipperton Island", keywords: ["flag", "clipperton", "island"] },
  { glyph: "🇨🇶", name: "flag: Sark", keywords: ["flag", "sark"] },
  { glyph: "🇨🇷", name: "flag: Costa Rica", keywords: ["flag", "costa", "rica"] },
  { glyph: "🇨🇺", name: "flag: Cuba", keywords: ["flag", "cuba", "cuban"] },
  { glyph: "🇨🇻", name: "flag: Cape Verde", keywords: ["flag", "cape", "verde"] },
  { glyph: "🇨🇼", name: "flag: Curaçao", keywords: ["flag", "curaao", "curacao"] },
  { glyph: "🇨🇽", name: "flag: Christmas Island", keywords: ["flag", "christmas", "island"] },
  { glyph: "🇨🇾", name: "flag: Cyprus", keywords: ["flag", "cyprus", "cypriot"] },
  { glyph: "🇨🇿", name: "flag: Czechia", keywords: ["flag", "czechia", "czech"] },
  { glyph: "🇩🇪", name: "flag: Germany", keywords: ["flag", "germany", "german"] },
  { glyph: "🇩🇬", name: "flag: Diego Garcia", keywords: ["flag", "diego", "garcia"] },
  { glyph: "🇩🇯", name: "flag: Djibouti", keywords: ["flag", "djibouti", "djiboutian"] },
  { glyph: "🇩🇰", name: "flag: Denmark", keywords: ["flag", "denmark", "danish"] },
  { glyph: "🇩🇲", name: "flag: Dominica", keywords: ["flag", "dominica"] },
  { glyph: "🇩🇴", name: "flag: Dominican Republic", keywords: ["flag", "dominican", "republic"] },
  { glyph: "🇩🇿", name: "flag: Algeria", keywords: ["flag", "algeria", "algerian"] },
  { glyph: "🇪🇦", name: "flag: Ceuta & Melilla", keywords: ["flag", "ceuta", "melilla"] },
  { glyph: "🇪🇨", name: "flag: Ecuador", keywords: ["flag", "ecuador", "ecuadorian"] },
  { glyph: "🇪🇪", name: "flag: Estonia", keywords: ["flag", "estonia", "estonian"] },
  { glyph: "🇪🇬", name: "flag: Egypt", keywords: ["flag", "egypt", "egyptian"] },
  { glyph: "🇪🇭", name: "flag: Western Sahara", keywords: ["flag", "western", "sahara"] },
  { glyph: "🇪🇷", name: "flag: Eritrea", keywords: ["flag", "eritrea", "eritrean"] },
  { glyph: "🇪🇸", name: "flag: Spain", keywords: ["flag", "spain", "spanish"] },
  { glyph: "🇪🇹", name: "flag: Ethiopia", keywords: ["flag", "ethiopia", "ethiopian"] },
  { glyph: "🇪🇺", name: "flag: European Union", keywords: ["flag", "european", "union", "europe"] },
  { glyph: "🇫🇮", name: "flag: Finland", keywords: ["flag", "finland", "finnish"] },
  { glyph: "🇫🇯", name: "flag: Fiji", keywords: ["flag", "fiji", "fijian"] },
  { glyph: "🇫🇰", name: "flag: Falkland Islands", keywords: ["flag", "falkland", "islands"] },
  { glyph: "🇫🇲", name: "flag: Micronesia", keywords: ["flag", "micronesia"] },
  { glyph: "🇫🇴", name: "flag: Faroe Islands", keywords: ["flag", "faroe", "islands"] },
  { glyph: "🇫🇷", name: "flag: France", keywords: ["flag", "france", "french"] },
  { glyph: "🇬🇦", name: "flag: Gabon", keywords: ["flag", "gabon", "gabonese"] },
  {
    glyph: "🇬🇧",
    name: "flag: United Kingdom",
    keywords: ["flag", "united", "kingdom", "uk", "britain", "british"],
  },
  { glyph: "🇬🇩", name: "flag: Grenada", keywords: ["flag", "grenada"] },
  { glyph: "🇬🇪", name: "flag: Georgia", keywords: ["flag", "georgia", "georgian"] },
  { glyph: "🇬🇫", name: "flag: French Guiana", keywords: ["flag", "french", "guiana"] },
  { glyph: "🇬🇬", name: "flag: Guernsey", keywords: ["flag", "guernsey"] },
  { glyph: "🇬🇭", name: "flag: Ghana", keywords: ["flag", "ghana", "ghanaian"] },
  { glyph: "🇬🇮", name: "flag: Gibraltar", keywords: ["flag", "gibraltar"] },
  { glyph: "🇬🇱", name: "flag: Greenland", keywords: ["flag", "greenland"] },
  { glyph: "🇬🇲", name: "flag: Gambia", keywords: ["flag", "gambia", "gambian"] },
  { glyph: "🇬🇳", name: "flag: Guinea", keywords: ["flag", "guinea", "guinean"] },
  { glyph: "🇬🇵", name: "flag: Guadeloupe", keywords: ["flag", "guadeloupe"] },
  { glyph: "🇬🇶", name: "flag: Equatorial Guinea", keywords: ["flag", "equatorial", "guinea"] },
  { glyph: "🇬🇷", name: "flag: Greece", keywords: ["flag", "greece", "greek"] },
  {
    glyph: "🇬🇸",
    name: "flag: South Georgia & South Sandwich Islands",
    keywords: ["flag", "south", "georgia", "south", "sandwich", "islands"],
  },
  { glyph: "🇬🇹", name: "flag: Guatemala", keywords: ["flag", "guatemala", "guatemalan"] },
  { glyph: "🇬🇺", name: "flag: Guam", keywords: ["flag", "guam"] },
  {
    glyph: "🇬🇼",
    name: "flag: Guinea-Bissau",
    keywords: ["flag", "guineabissau", "guinea", "bissau"],
  },
  { glyph: "🇬🇾", name: "flag: Guyana", keywords: ["flag", "guyana", "guyanese"] },
  {
    glyph: "🇭🇰",
    name: "flag: Hong Kong SAR China",
    keywords: ["flag", "hong", "kong", "sar", "china"],
  },
  {
    glyph: "🇭🇲",
    name: "flag: Heard & McDonald Islands",
    keywords: ["flag", "heard", "mcdonald", "islands"],
  },
  { glyph: "🇭🇳", name: "flag: Honduras", keywords: ["flag", "honduras", "honduran"] },
  { glyph: "🇭🇷", name: "flag: Croatia", keywords: ["flag", "croatia", "croatian"] },
  { glyph: "🇭🇹", name: "flag: Haiti", keywords: ["flag", "haiti", "haitian"] },
  { glyph: "🇭🇺", name: "flag: Hungary", keywords: ["flag", "hungary", "hungarian"] },
  { glyph: "🇮🇨", name: "flag: Canary Islands", keywords: ["flag", "canary", "islands"] },
  { glyph: "🇮🇩", name: "flag: Indonesia", keywords: ["flag", "indonesia", "indonesian"] },
  { glyph: "🇮🇪", name: "flag: Ireland", keywords: ["flag", "ireland", "irish"] },
  { glyph: "🇮🇱", name: "flag: Israel", keywords: ["flag", "israel", "israeli"] },
  { glyph: "🇮🇲", name: "flag: Isle of Man", keywords: ["flag", "isle", "man"] },
  { glyph: "🇮🇳", name: "flag: India", keywords: ["flag", "india", "indian"] },
  {
    glyph: "🇮🇴",
    name: "flag: British Indian Ocean Territory",
    keywords: ["flag", "british", "indian", "ocean", "territory"],
  },
  { glyph: "🇮🇶", name: "flag: Iraq", keywords: ["flag", "iraq", "iraqi"] },
  { glyph: "🇮🇷", name: "flag: Iran", keywords: ["flag", "iran", "iranian"] },
  { glyph: "🇮🇸", name: "flag: Iceland", keywords: ["flag", "iceland", "icelandic"] },
  { glyph: "🇮🇹", name: "flag: Italy", keywords: ["flag", "italy", "italian"] },
  { glyph: "🇯🇪", name: "flag: Jersey", keywords: ["flag", "jersey"] },
  { glyph: "🇯🇲", name: "flag: Jamaica", keywords: ["flag", "jamaica", "jamaican"] },
  { glyph: "🇯🇴", name: "flag: Jordan", keywords: ["flag", "jordan", "jordanian"] },
  { glyph: "🇯🇵", name: "flag: Japan", keywords: ["flag", "japan", "japanese"] },
  { glyph: "🇰🇪", name: "flag: Kenya", keywords: ["flag", "kenya", "kenyan"] },
  { glyph: "🇰🇬", name: "flag: Kyrgyzstan", keywords: ["flag", "kyrgyzstan"] },
  { glyph: "🇰🇭", name: "flag: Cambodia", keywords: ["flag", "cambodia", "cambodian"] },
  { glyph: "🇰🇮", name: "flag: Kiribati", keywords: ["flag", "kiribati"] },
  { glyph: "🇰🇲", name: "flag: Comoros", keywords: ["flag", "comoros", "comorian"] },
  { glyph: "🇰🇳", name: "flag: St. Kitts & Nevis", keywords: ["flag", "kitts", "nevis"] },
  { glyph: "🇰🇵", name: "flag: North Korea", keywords: ["flag", "north", "korea"] },
  { glyph: "🇰🇷", name: "flag: South Korea", keywords: ["flag", "south", "korea", "korean"] },
  { glyph: "🇰🇼", name: "flag: Kuwait", keywords: ["flag", "kuwait", "kuwaiti"] },
  { glyph: "🇰🇾", name: "flag: Cayman Islands", keywords: ["flag", "cayman", "islands"] },
  { glyph: "🇰🇿", name: "flag: Kazakhstan", keywords: ["flag", "kazakhstan", "kazakh"] },
  { glyph: "🇱🇦", name: "flag: Laos", keywords: ["flag", "laos", "laotian"] },
  { glyph: "🇱🇧", name: "flag: Lebanon", keywords: ["flag", "lebanon", "lebanese"] },
  { glyph: "🇱🇨", name: "flag: St. Lucia", keywords: ["flag", "lucia", "saint"] },
  { glyph: "🇱🇮", name: "flag: Liechtenstein", keywords: ["flag", "liechtenstein"] },
  { glyph: "🇱🇰", name: "flag: Sri Lanka", keywords: ["flag", "sri", "lanka"] },
  { glyph: "🇱🇷", name: "flag: Liberia", keywords: ["flag", "liberia", "liberian"] },
  { glyph: "🇱🇸", name: "flag: Lesotho", keywords: ["flag", "lesotho"] },
  { glyph: "🇱🇹", name: "flag: Lithuania", keywords: ["flag", "lithuania", "lithuanian"] },
  { glyph: "🇱🇺", name: "flag: Luxembourg", keywords: ["flag", "luxembourg", "luxembourgish"] },
  { glyph: "🇱🇻", name: "flag: Latvia", keywords: ["flag", "latvia", "latvian"] },
  { glyph: "🇱🇾", name: "flag: Libya", keywords: ["flag", "libya", "libyan"] },
  { glyph: "🇲🇦", name: "flag: Morocco", keywords: ["flag", "morocco", "moroccan"] },
  { glyph: "🇲🇨", name: "flag: Monaco", keywords: ["flag", "monaco", "monegasque"] },
  { glyph: "🇲🇩", name: "flag: Moldova", keywords: ["flag", "moldova", "moldovan"] },
  { glyph: "🇲🇪", name: "flag: Montenegro", keywords: ["flag", "montenegro", "montenegrin"] },
  { glyph: "🇲🇫", name: "flag: St. Martin", keywords: ["flag", "martin"] },
  { glyph: "🇲🇬", name: "flag: Madagascar", keywords: ["flag", "madagascar", "malagasy"] },
  { glyph: "🇲🇭", name: "flag: Marshall Islands", keywords: ["flag", "marshall", "islands"] },
  { glyph: "🇲🇰", name: "flag: North Macedonia", keywords: ["flag", "north", "macedonia"] },
  { glyph: "🇲🇱", name: "flag: Mali", keywords: ["flag", "mali", "malian"] },
  { glyph: "🇲🇲", name: "flag: Myanmar (Burma)", keywords: ["flag", "myanmar", "burma"] },
  { glyph: "🇲🇳", name: "flag: Mongolia", keywords: ["flag", "mongolia", "mongolian"] },
  { glyph: "🇲🇴", name: "flag: Macao SAR China", keywords: ["flag", "macao", "sar", "china"] },
  {
    glyph: "🇲🇵",
    name: "flag: Northern Mariana Islands",
    keywords: ["flag", "northern", "mariana", "islands"],
  },
  { glyph: "🇲🇶", name: "flag: Martinique", keywords: ["flag", "martinique"] },
  { glyph: "🇲🇷", name: "flag: Mauritania", keywords: ["flag", "mauritania", "mauritanian"] },
  { glyph: "🇲🇸", name: "flag: Montserrat", keywords: ["flag", "montserrat"] },
  { glyph: "🇲🇹", name: "flag: Malta", keywords: ["flag", "malta", "maltese"] },
  { glyph: "🇲🇺", name: "flag: Mauritius", keywords: ["flag", "mauritius", "mauritian"] },
  { glyph: "🇲🇻", name: "flag: Maldives", keywords: ["flag", "maldives"] },
  { glyph: "🇲🇼", name: "flag: Malawi", keywords: ["flag", "malawi"] },
  { glyph: "🇲🇽", name: "flag: Mexico", keywords: ["flag", "mexico", "mexican"] },
  { glyph: "🇲🇾", name: "flag: Malaysia", keywords: ["flag", "malaysia", "malaysian"] },
  { glyph: "🇲🇿", name: "flag: Mozambique", keywords: ["flag", "mozambique", "mozambican"] },
  { glyph: "🇳🇦", name: "flag: Namibia", keywords: ["flag", "namibia", "namibian"] },
  { glyph: "🇳🇨", name: "flag: New Caledonia", keywords: ["flag", "new", "caledonia"] },
  { glyph: "🇳🇪", name: "flag: Niger", keywords: ["flag", "niger", "nigerien"] },
  { glyph: "🇳🇫", name: "flag: Norfolk Island", keywords: ["flag", "norfolk", "island"] },
  { glyph: "🇳🇬", name: "flag: Nigeria", keywords: ["flag", "nigeria", "nigerian"] },
  { glyph: "🇳🇮", name: "flag: Nicaragua", keywords: ["flag", "nicaragua", "nicaraguan"] },
  { glyph: "🇳🇱", name: "flag: Netherlands", keywords: ["flag", "netherlands", "dutch"] },
  { glyph: "🇳🇴", name: "flag: Norway", keywords: ["flag", "norway", "norwegian"] },
  { glyph: "🇳🇵", name: "flag: Nepal", keywords: ["flag", "nepal", "nepali"] },
  { glyph: "🇳🇷", name: "flag: Nauru", keywords: ["flag", "nauru"] },
  { glyph: "🇳🇺", name: "flag: Niue", keywords: ["flag", "niue"] },
  { glyph: "🇳🇿", name: "flag: New Zealand", keywords: ["flag", "new", "zealand"] },
  { glyph: "🇴🇲", name: "flag: Oman", keywords: ["flag", "oman", "omani"] },
  { glyph: "🇵🇦", name: "flag: Panama", keywords: ["flag", "panama", "panamanian"] },
  { glyph: "🇵🇪", name: "flag: Peru", keywords: ["flag", "peru", "peruvian"] },
  { glyph: "🇵🇫", name: "flag: French Polynesia", keywords: ["flag", "french", "polynesia"] },
  { glyph: "🇵🇬", name: "flag: Papua New Guinea", keywords: ["flag", "papua", "new", "guinea"] },
  { glyph: "🇵🇭", name: "flag: Philippines", keywords: ["flag", "philippines", "filipino"] },
  { glyph: "🇵🇰", name: "flag: Pakistan", keywords: ["flag", "pakistan", "pakistani"] },
  { glyph: "🇵🇱", name: "flag: Poland", keywords: ["flag", "poland"] },
  { glyph: "🇵🇲", name: "flag: St. Pierre & Miquelon", keywords: ["flag", "pierre", "miquelon"] },
  { glyph: "🇵🇳", name: "flag: Pitcairn Islands", keywords: ["flag", "pitcairn", "islands"] },
  { glyph: "🇵🇷", name: "flag: Puerto Rico", keywords: ["flag", "puerto", "rico"] },
  {
    glyph: "🇵🇸",
    name: "flag: Palestinian Territories",
    keywords: ["flag", "palestinian", "territories", "palestine"],
  },
  { glyph: "🇵🇹", name: "flag: Portugal", keywords: ["flag", "portugal", "portuguese"] },
  { glyph: "🇵🇼", name: "flag: Palau", keywords: ["flag", "palau"] },
  { glyph: "🇵🇾", name: "flag: Paraguay", keywords: ["flag", "paraguay", "paraguayan"] },
  { glyph: "🇶🇦", name: "flag: Qatar", keywords: ["flag", "qatar", "qatari"] },
  { glyph: "🇷🇪", name: "flag: Réunion", keywords: ["flag", "runion"] },
  { glyph: "🇷🇴", name: "flag: Romania", keywords: ["flag", "romania", "romanian"] },
  { glyph: "🇷🇸", name: "flag: Serbia", keywords: ["flag", "serbia", "serbian"] },
  { glyph: "🇷🇺", name: "flag: Russia", keywords: ["flag", "russia", "russian"] },
  { glyph: "🇷🇼", name: "flag: Rwanda", keywords: ["flag", "rwanda", "rwandan"] },
  { glyph: "🇸🇦", name: "flag: Saudi Arabia", keywords: ["flag", "saudi", "arabia"] },
  { glyph: "🇸🇧", name: "flag: Solomon Islands", keywords: ["flag", "solomon", "islands"] },
  { glyph: "🇸🇨", name: "flag: Seychelles", keywords: ["flag", "seychelles", "seychellois"] },
  { glyph: "🇸🇩", name: "flag: Sudan", keywords: ["flag", "sudan", "sudanese"] },
  { glyph: "🇸🇪", name: "flag: Sweden", keywords: ["flag", "sweden", "swedish"] },
  { glyph: "🇸🇬", name: "flag: Singapore", keywords: ["flag", "singapore", "singaporean"] },
  { glyph: "🇸🇭", name: "flag: St. Helena", keywords: ["flag", "helena", "saint"] },
  { glyph: "🇸🇮", name: "flag: Slovenia", keywords: ["flag", "slovenia", "slovenian"] },
  {
    glyph: "🇸🇯",
    name: "flag: Svalbard & Jan Mayen",
    keywords: ["flag", "svalbard", "jan", "mayen"],
  },
  { glyph: "🇸🇰", name: "flag: Slovakia", keywords: ["flag", "slovakia", "slovak"] },
  { glyph: "🇸🇱", name: "flag: Sierra Leone", keywords: ["flag", "sierra", "leone"] },
  { glyph: "🇸🇲", name: "flag: San Marino", keywords: ["flag", "san", "marino"] },
  { glyph: "🇸🇳", name: "flag: Senegal", keywords: ["flag", "senegal", "senegalese"] },
  { glyph: "🇸🇴", name: "flag: Somalia", keywords: ["flag", "somalia", "somali"] },
  { glyph: "🇸🇷", name: "flag: Suriname", keywords: ["flag", "suriname", "surinamese"] },
  { glyph: "🇸🇸", name: "flag: South Sudan", keywords: ["flag", "south", "sudan"] },
  {
    glyph: "🇸🇹",
    name: "flag: São Tomé & Príncipe",
    keywords: ["flag", "tom", "prncipe", "sao", "tome", "principe"],
  },
  { glyph: "🇸🇻", name: "flag: El Salvador", keywords: ["flag", "salvador"] },
  { glyph: "🇸🇽", name: "flag: Sint Maarten", keywords: ["flag", "sint", "maarten"] },
  { glyph: "🇸🇾", name: "flag: Syria", keywords: ["flag", "syria", "syrian"] },
  { glyph: "🇸🇿", name: "flag: Eswatini", keywords: ["flag", "eswatini", "swaziland"] },
  { glyph: "🇹🇦", name: "flag: Tristan da Cunha", keywords: ["flag", "tristan", "cunha"] },
  {
    glyph: "🇹🇨",
    name: "flag: Turks & Caicos Islands",
    keywords: ["flag", "turks", "caicos", "islands"],
  },
  { glyph: "🇹🇩", name: "flag: Chad", keywords: ["flag", "chad"] },
  {
    glyph: "🇹🇫",
    name: "flag: French Southern Territories",
    keywords: ["flag", "french", "southern", "territories"],
  },
  { glyph: "🇹🇬", name: "flag: Togo", keywords: ["flag", "togo", "togolese"] },
  { glyph: "🇹🇭", name: "flag: Thailand", keywords: ["flag", "thailand", "thai"] },
  { glyph: "🇹🇯", name: "flag: Tajikistan", keywords: ["flag", "tajikistan"] },
  { glyph: "🇹🇰", name: "flag: Tokelau", keywords: ["flag", "tokelau"] },
  {
    glyph: "🇹🇱",
    name: "flag: Timor-Leste",
    keywords: ["flag", "timorleste", "timor", "leste", "east"],
  },
  { glyph: "🇹🇲", name: "flag: Turkmenistan", keywords: ["flag", "turkmenistan"] },
  { glyph: "🇹🇳", name: "flag: Tunisia", keywords: ["flag", "tunisia", "tunisian"] },
  { glyph: "🇹🇴", name: "flag: Tonga", keywords: ["flag", "tonga"] },
  { glyph: "🇹🇷", name: "flag: Türkiye", keywords: ["flag", "trkiye", "turkey", "turkish"] },
  { glyph: "🇹🇹", name: "flag: Trinidad & Tobago", keywords: ["flag", "trinidad", "tobago"] },
  { glyph: "🇹🇻", name: "flag: Tuvalu", keywords: ["flag", "tuvalu"] },
  { glyph: "🇹🇼", name: "flag: Taiwan", keywords: ["flag", "taiwan", "taiwanese"] },
  { glyph: "🇹🇿", name: "flag: Tanzania", keywords: ["flag", "tanzania", "tanzanian"] },
  { glyph: "🇺🇦", name: "flag: Ukraine", keywords: ["flag", "ukraine", "ukrainian"] },
  { glyph: "🇺🇬", name: "flag: Uganda", keywords: ["flag", "uganda", "ugandan"] },
  { glyph: "🇺🇲", name: "flag: U.S. Outlying Islands", keywords: ["flag", "outlying", "islands"] },
  { glyph: "🇺🇳", name: "flag: United Nations", keywords: ["flag", "united", "nations"] },
  {
    glyph: "🇺🇸",
    name: "flag: United States",
    keywords: ["flag", "united", "states", "usa", "america"],
  },
  { glyph: "🇺🇾", name: "flag: Uruguay", keywords: ["flag", "uruguay", "uruguayan"] },
  { glyph: "🇺🇿", name: "flag: Uzbekistan", keywords: ["flag", "uzbekistan", "uzbek"] },
  { glyph: "🇻🇦", name: "flag: Vatican City", keywords: ["flag", "vatican", "city"] },
  {
    glyph: "🇻🇨",
    name: "flag: St. Vincent & Grenadines",
    keywords: ["flag", "vincent", "grenadines"],
  },
  { glyph: "🇻🇪", name: "flag: Venezuela", keywords: ["flag", "venezuela", "venezuelan"] },
  {
    glyph: "🇻🇬",
    name: "flag: British Virgin Islands",
    keywords: ["flag", "british", "virgin", "islands"],
  },
  { glyph: "🇻🇮", name: "flag: U.S. Virgin Islands", keywords: ["flag", "virgin", "islands", "us"] },
  { glyph: "🇻🇳", name: "flag: Vietnam", keywords: ["flag", "vietnam", "vietnamese"] },
  { glyph: "🇻🇺", name: "flag: Vanuatu", keywords: ["flag", "vanuatu"] },
  { glyph: "🇼🇫", name: "flag: Wallis & Futuna", keywords: ["flag", "wallis", "futuna"] },
  { glyph: "🇼🇸", name: "flag: Samoa", keywords: ["flag", "samoa"] },
  { glyph: "🇽🇰", name: "flag: Kosovo", keywords: ["flag", "kosovo", "kosovar"] },
  { glyph: "🇾🇪", name: "flag: Yemen", keywords: ["flag", "yemen", "yemeni"] },
  { glyph: "🇾🇹", name: "flag: Mayotte", keywords: ["flag", "mayotte"] },
  { glyph: "🇿🇦", name: "flag: South Africa", keywords: ["flag", "south", "africa"] },
  { glyph: "🇿🇲", name: "flag: Zambia", keywords: ["flag", "zambia", "zambian"] },
  { glyph: "🇿🇼", name: "flag: Zimbabwe", keywords: ["flag", "zimbabwe", "zimbabwean"] },
]
